# coding: utf-8

"""
    Asterwise API

    Astrology and divination API — Vedic and Western astrology, numerology, tarot, crystals, dreams, and horoscopes. Send birth data, get accurate calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asterwise.models.ishta_devta_response import IshtaDevtaResponse

class TestIshtaDevtaResponse(unittest.TestCase):
    """IshtaDevtaResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IshtaDevtaResponse:
        """Test IshtaDevtaResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IshtaDevtaResponse`
        """
        model = IshtaDevtaResponse()
        if include_optional:
            return IshtaDevtaResponse(
                atmakaraka = '',
                karakamsha_lagna = '',
                karakamsha_lagna_index = 56,
                jivanmuktamsa_planet = '',
                navamsa_lagna = '',
                navamsa_lagna_index = 56,
                twelfth_house_sign = '',
                twelfth_house_index = 56,
                planets_in_12th = [
                    ''
                    ],
                ishta_devta_planet = '',
                deity = '',
                description = '',
                method = '',
                d9_positions = { }
            )
        else:
            return IshtaDevtaResponse(
                atmakaraka = '',
                karakamsha_lagna = '',
                karakamsha_lagna_index = 56,
                navamsa_lagna = '',
                navamsa_lagna_index = 56,
                twelfth_house_sign = '',
                twelfth_house_index = 56,
                planets_in_12th = [
                    ''
                    ],
                ishta_devta_planet = '',
                deity = '',
                description = '',
                method = '',
                d9_positions = { },
        )
        """

    def testIshtaDevtaResponse(self):
        """Test IshtaDevtaResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
