# coding: utf-8

"""
    Asterwise API

    Astrology and divination API — Vedic and Western astrology, numerology, tarot, crystals, dreams, and horoscopes. Send birth data, get accurate calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asterwise.models.biorhythm_range_response import BiorhythmRangeResponse

class TestBiorhythmRangeResponse(unittest.TestCase):
    """BiorhythmRangeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BiorhythmRangeResponse:
        """Test BiorhythmRangeResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BiorhythmRangeResponse`
        """
        model = BiorhythmRangeResponse()
        if include_optional:
            return BiorhythmRangeResponse(
                birth_date = '',
                start_date = '',
                end_date = '',
                days = 56,
                daily = [
                    asterwise.models.biorhythm_daily_entry.BiorhythmDailyEntry(
                        date = '', 
                        cycles = {
                            'key' : asterwise.models.biorhythm_cycle_detail.BiorhythmCycleDetail(
                                value = 1.337, 
                                percentage = 1.337, 
                                phase = '', 
                                is_critical = True, 
                                cycle_length_days = 56, 
                                description = '', )
                            }, 
                        critical = [
                            ''
                            ], 
                        composite_score = 1.337, )
                    ],
                note = ''
            )
        else:
            return BiorhythmRangeResponse(
                birth_date = '',
                start_date = '',
                end_date = '',
                days = 56,
                daily = [
                    asterwise.models.biorhythm_daily_entry.BiorhythmDailyEntry(
                        date = '', 
                        cycles = {
                            'key' : asterwise.models.biorhythm_cycle_detail.BiorhythmCycleDetail(
                                value = 1.337, 
                                percentage = 1.337, 
                                phase = '', 
                                is_critical = True, 
                                cycle_length_days = 56, 
                                description = '', )
                            }, 
                        critical = [
                            ''
                            ], 
                        composite_score = 1.337, )
                    ],
                note = '',
        )
        """

    def testBiorhythmRangeResponse(self):
        """Test BiorhythmRangeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
