# coding: utf-8

"""
    Asterwise API

    Astrology and divination API — Vedic and Western astrology, numerology, tarot, crystals, dreams, and horoscopes. Send birth data, get accurate calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asterwise.models.pitru_dosha_response import PitruDoshaResponse

class TestPitruDoshaResponse(unittest.TestCase):
    """PitruDoshaResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PitruDoshaResponse:
        """Test PitruDoshaResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PitruDoshaResponse`
        """
        model = PitruDoshaResponse()
        if include_optional:
            return PitruDoshaResponse(
                present = True,
                severity = '',
                severity_note = '',
                combinations_triggered = [
                    ''
                    ],
                combinations_count = 56,
                sun_analysis = asterwise.models.pitru_sun_analysis.PitruSunAnalysis(
                    house = 56, 
                    sign_index = 56, 
                    debilitated = True, 
                    afflictions = [
                        ''
                        ], ),
                ninth_lord_analysis = asterwise.models.pitru_ninth_lord_analysis.PitruNinthLordAnalysis(
                    planet = '', 
                    house = 56, 
                    sign_index = 56, 
                    debilitated = True, 
                    afflictions = [
                        ''
                        ], ),
                all_factors = [
                    ''
                    ],
                cancellations = [
                    ''
                    ],
                interpretation = '',
                classical_symptoms = [
                    ''
                    ],
                remedies = [
                    ''
                    ]
            )
        else:
            return PitruDoshaResponse(
                present = True,
                combinations_triggered = [
                    ''
                    ],
                combinations_count = 56,
                sun_analysis = asterwise.models.pitru_sun_analysis.PitruSunAnalysis(
                    house = 56, 
                    sign_index = 56, 
                    debilitated = True, 
                    afflictions = [
                        ''
                        ], ),
                ninth_lord_analysis = asterwise.models.pitru_ninth_lord_analysis.PitruNinthLordAnalysis(
                    planet = '', 
                    house = 56, 
                    sign_index = 56, 
                    debilitated = True, 
                    afflictions = [
                        ''
                        ], ),
                all_factors = [
                    ''
                    ],
                cancellations = [
                    ''
                    ],
                interpretation = '',
                classical_symptoms = [
                    ''
                    ],
                remedies = [
                    ''
                    ],
        )
        """

    def testPitruDoshaResponse(self):
        """Test PitruDoshaResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
