# coding: utf-8

"""
    Asterwise API

    Vedic astrology, numerology, horoscope, and PDF report API. Send birth data, get accurate sidereal calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asterwise.models.api_response_choghadiya_response import ApiResponseChoghadiyaResponse

class TestApiResponseChoghadiyaResponse(unittest.TestCase):
    """ApiResponseChoghadiyaResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiResponseChoghadiyaResponse:
        """Test ApiResponseChoghadiyaResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiResponseChoghadiyaResponse`
        """
        model = ApiResponseChoghadiyaResponse()
        if include_optional:
            return ApiResponseChoghadiyaResponse(
                success = True,
                message = 'success',
                data = asterwise.models.choghadiya_response.ChoghadiyaResponse(
                    date = '', 
                    sunrise = '', 
                    sunset = '', 
                    day_choghadiya = [
                        asterwise.models.choghadiya_period.ChoghadiyaPeriod(
                            period = 56, 
                            name = '', 
                            type = '', 
                            ruling_planet = '', 
                            suitable_for = '', 
                            start = '', 
                            end = '', 
                            is_current = True, )
                        ], 
                    night_choghadiya = [
                        asterwise.models.choghadiya_period.ChoghadiyaPeriod(
                            period = 56, 
                            name = '', 
                            type = '', 
                            ruling_planet = '', 
                            suitable_for = '', 
                            start = '', 
                            end = '', 
                            is_current = True, )
                        ], )
            )
        else:
            return ApiResponseChoghadiyaResponse(
                data = asterwise.models.choghadiya_response.ChoghadiyaResponse(
                    date = '', 
                    sunrise = '', 
                    sunset = '', 
                    day_choghadiya = [
                        asterwise.models.choghadiya_period.ChoghadiyaPeriod(
                            period = 56, 
                            name = '', 
                            type = '', 
                            ruling_planet = '', 
                            suitable_for = '', 
                            start = '', 
                            end = '', 
                            is_current = True, )
                        ], 
                    night_choghadiya = [
                        asterwise.models.choghadiya_period.ChoghadiyaPeriod(
                            period = 56, 
                            name = '', 
                            type = '', 
                            ruling_planet = '', 
                            suitable_for = '', 
                            start = '', 
                            end = '', 
                            is_current = True, )
                        ], ),
        )
        """

    def testApiResponseChoghadiyaResponse(self):
        """Test ApiResponseChoghadiyaResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
