# coding: utf-8

"""
    Asterwise API

    Astrology and divination API — Vedic and Western astrology, numerology, tarot, crystals, dreams, and horoscopes. Send birth data, get accurate calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asterwise.models.muhurta_window import MuhurtaWindow

class TestMuhurtaWindow(unittest.TestCase):
    """MuhurtaWindow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MuhurtaWindow:
        """Test MuhurtaWindow
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MuhurtaWindow`
        """
        model = MuhurtaWindow()
        if include_optional:
            return MuhurtaWindow(
                var_date = '',
                start = '',
                end = '',
                score = 56,
                choghadiya = '',
                choghadiya_type = '',
                yoga = '',
                vara = '',
                vara_number = 56,
                tithi = '',
                tithi_number = 56,
                reason = '',
                is_rahu_kaal = True,
                is_abhijit = True,
                is_amrita_siddhi = True,
                is_sarvartha_siddhi = True,
                start_at = '',
                end_at = '',
                civil_date = '',
                panchanga_day = '',
                duration_minutes = 1.337,
                grade = '',
                paksha = '',
                nakshatra = asterwise.models.muhurta_named.MuhurtaNamed(
                    number = 56, 
                    name = '', ),
                yoga_number = 56,
                karana = '',
                vara_lord = '',
                lagna = asterwise.models.muhurta_lagna.MuhurtaLagna(
                    index = 56, 
                    name = '', ),
                masa = '',
                is_guru_pushya = True,
                is_ravi_pushya = True,
                reasons = [
                    ''
                    ],
                cautions = [
                    ''
                    ],
                tarabala = [
                    asterwise.models.muhurta_tara.MuhurtaTara(
                        participant = '', 
                        tara = '', 
                        count_from_birth = 56, 
                        is_favorable = True, )
                    ],
                chandrabala = [
                    asterwise.models.muhurta_chandra.MuhurtaChandra(
                        participant = '', 
                        moon_house = 56, 
                        is_favorable = True, )
                    ]
            )
        else:
            return MuhurtaWindow(
                var_date = '',
                start = '',
                end = '',
                score = 56,
                choghadiya = '',
                choghadiya_type = '',
                yoga = '',
                vara = '',
                vara_number = 56,
                tithi = '',
                tithi_number = 56,
                reason = '',
                is_rahu_kaal = True,
                is_abhijit = True,
                is_amrita_siddhi = True,
                is_sarvartha_siddhi = True,
                start_at = '',
                end_at = '',
                civil_date = '',
                panchanga_day = '',
                duration_minutes = 1.337,
                grade = '',
                paksha = '',
                nakshatra = asterwise.models.muhurta_named.MuhurtaNamed(
                    number = 56, 
                    name = '', ),
                yoga_number = 56,
                karana = '',
                vara_lord = '',
                masa = '',
                is_guru_pushya = True,
                is_ravi_pushya = True,
                reasons = [
                    ''
                    ],
                cautions = [
                    ''
                    ],
        )
        """

    def testMuhurtaWindow(self):
        """Test MuhurtaWindow"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
