# coding: utf-8

"""
    Asterwise API

    Vedic astrology, numerology, horoscope, and PDF report API. Send birth data, get accurate sidereal calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asterwise.models.api_response_ashtakavarga_response import ApiResponseAshtakavargaResponse

class TestApiResponseAshtakavargaResponse(unittest.TestCase):
    """ApiResponseAshtakavargaResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiResponseAshtakavargaResponse:
        """Test ApiResponseAshtakavargaResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiResponseAshtakavargaResponse`
        """
        model = ApiResponseAshtakavargaResponse()
        if include_optional:
            return ApiResponseAshtakavargaResponse(
                success = True,
                message = 'success',
                data = asterwise.models.ashtakavarga_response.AshtakavargaResponse(
                    bhinna = {
                        'key' : {
                            'key' : 56
                            }
                        }, 
                    bhinna_after_trikona = {
                        'key' : {
                            'key' : 56
                            }
                        }, 
                    bhinna_after_ekadhipatya = {
                        'key' : {
                            'key' : 56
                            }
                        }, 
                    sarva = {
                        'key' : 56
                        }, 
                    sarva_reduced = {
                        'key' : 56
                        }, 
                    after_trikona = {
                        'key' : 56
                        }, 
                    after_ekadhipatya = {
                        'key' : 56
                        }, 
                    birth_time_unknown = True, 
                    fallback_method = '', )
            )
        else:
            return ApiResponseAshtakavargaResponse(
                data = asterwise.models.ashtakavarga_response.AshtakavargaResponse(
                    bhinna = {
                        'key' : {
                            'key' : 56
                            }
                        }, 
                    bhinna_after_trikona = {
                        'key' : {
                            'key' : 56
                            }
                        }, 
                    bhinna_after_ekadhipatya = {
                        'key' : {
                            'key' : 56
                            }
                        }, 
                    sarva = {
                        'key' : 56
                        }, 
                    sarva_reduced = {
                        'key' : 56
                        }, 
                    after_trikona = {
                        'key' : 56
                        }, 
                    after_ekadhipatya = {
                        'key' : 56
                        }, 
                    birth_time_unknown = True, 
                    fallback_method = '', ),
        )
        """

    def testApiResponseAshtakavargaResponse(self):
        """Test ApiResponseAshtakavargaResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
