# coding: utf-8

"""
    Asterwise API

    Astrology and divination API — Vedic and Western astrology, numerology, tarot, crystals, dreams, and horoscopes. Send birth data, get accurate calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asterwise.models.name_correction_name_score import NameCorrectionNameScore

class TestNameCorrectionNameScore(unittest.TestCase):
    """NameCorrectionNameScore unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NameCorrectionNameScore:
        """Test NameCorrectionNameScore
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NameCorrectionNameScore`
        """
        model = NameCorrectionNameScore()
        if include_optional:
            return NameCorrectionNameScore(
                name = '',
                expression = 56,
                soul_urge = 56,
                personality = 56,
                is_master = True,
                karmic_debt = 56,
                compatibility = '',
                harmony_score = 56
            )
        else:
            return NameCorrectionNameScore(
                name = '',
                expression = 56,
                soul_urge = 56,
                personality = 56,
                is_master = True,
                compatibility = '',
                harmony_score = 56,
        )
        """

    def testNameCorrectionNameScore(self):
        """Test NameCorrectionNameScore"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
