# coding: utf-8

"""
    Asterwise API

    Vedic astrology, numerology, horoscope, and PDF report API. Send birth data, get accurate sidereal calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asterwise.models.kp_ruling_planets_request import KPRulingPlanetsRequest

class TestKPRulingPlanetsRequest(unittest.TestCase):
    """KPRulingPlanetsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KPRulingPlanetsRequest:
        """Test KPRulingPlanetsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KPRulingPlanetsRequest`
        """
        model = KPRulingPlanetsRequest()
        if include_optional:
            return KPRulingPlanetsRequest(
                latitude = 1.337,
                longitude = 1.337,
                target_date = '',
                target_time = '',
                target_timezone = ''
            )
        else:
            return KPRulingPlanetsRequest(
                latitude = 1.337,
                longitude = 1.337,
        )
        """

    def testKPRulingPlanetsRequest(self):
        """Test KPRulingPlanetsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
