# coding: utf-8

"""
    Asterwise API

    Astrology and divination API — Vedic and Western astrology, numerology, tarot, crystals, dreams, and horoscopes. Send birth data, get accurate calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asterwise.models.ayanamsha_response import AyanamshaResponse

class TestAyanamshaResponse(unittest.TestCase):
    """AyanamshaResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AyanamshaResponse:
        """Test AyanamshaResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AyanamshaResponse`
        """
        model = AyanamshaResponse()
        if include_optional:
            return AyanamshaResponse(
                var_date = '',
                ayanamsha = {
                    'key' : asterwise.models.ayanamsha_system_value.AyanamshaSystemValue(
                        value_decimal = 1.337, 
                        degrees = 56, 
                        minutes = 56, 
                        seconds = 1.337, 
                        dms = '', 
                        description = '', )
                    },
                note = ''
            )
        else:
            return AyanamshaResponse(
                var_date = '',
                ayanamsha = {
                    'key' : asterwise.models.ayanamsha_system_value.AyanamshaSystemValue(
                        value_decimal = 1.337, 
                        degrees = 56, 
                        minutes = 56, 
                        seconds = 1.337, 
                        dms = '', 
                        description = '', )
                    },
                note = '',
        )
        """

    def testAyanamshaResponse(self):
        """Test AyanamshaResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
