# coding: utf-8

"""
    Asterwise API

    Vedic astrology, numerology, horoscope, and PDF report API. Send birth data, get accurate sidereal calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asterwise.models.calendar_day import CalendarDay

class TestCalendarDay(unittest.TestCase):
    """CalendarDay unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CalendarDay:
        """Test CalendarDay
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CalendarDay`
        """
        model = CalendarDay()
        if include_optional:
            return CalendarDay(
                var_date = '',
                tithi = asterwise.models.calendar_tithi.CalendarTithi(
                    name = '', 
                    number = 56, 
                    paksha = '', 
                    end_time = '', ),
                vara = asterwise.models.calendar_vara.CalendarVara(
                    name = '', 
                    number = 56, 
                    lord = '', ),
                nakshatra = asterwise.models.calendar_nakshatra.CalendarNakshatra(
                    name = '', 
                    index = 56, 
                    pada = 56, 
                    end_time = '', ),
                yoga = asterwise.models.calendar_yoga.CalendarYoga(
                    name = '', 
                    index = 56, 
                    is_inauspicious = True, 
                    end_time = '', ),
                karana = asterwise.models.calendar_karana.CalendarKarana(
                    name = '', 
                    number = 56, 
                    end_time = '', ),
                rahu_kaal = asterwise.models.calendar_rahu_kaal.CalendarRahuKaal(
                    start = '', 
                    end = '', )
            )
        else:
            return CalendarDay(
                var_date = '',
                tithi = asterwise.models.calendar_tithi.CalendarTithi(
                    name = '', 
                    number = 56, 
                    paksha = '', 
                    end_time = '', ),
                vara = asterwise.models.calendar_vara.CalendarVara(
                    name = '', 
                    number = 56, 
                    lord = '', ),
                nakshatra = asterwise.models.calendar_nakshatra.CalendarNakshatra(
                    name = '', 
                    index = 56, 
                    pada = 56, 
                    end_time = '', ),
                yoga = asterwise.models.calendar_yoga.CalendarYoga(
                    name = '', 
                    index = 56, 
                    is_inauspicious = True, 
                    end_time = '', ),
                karana = asterwise.models.calendar_karana.CalendarKarana(
                    name = '', 
                    number = 56, 
                    end_time = '', ),
                rahu_kaal = asterwise.models.calendar_rahu_kaal.CalendarRahuKaal(
                    start = '', 
                    end = '', ),
        )
        """

    def testCalendarDay(self):
        """Test CalendarDay"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
