# coding: utf-8

"""
    Asterwise API

    Astrology and divination API — Vedic and Western astrology, numerology, tarot, crystals, dreams, and horoscopes. Send birth data, get accurate calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asterwise.models.planet_nature_all_response import PlanetNatureAllResponse

class TestPlanetNatureAllResponse(unittest.TestCase):
    """PlanetNatureAllResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlanetNatureAllResponse:
        """Test PlanetNatureAllResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlanetNatureAllResponse`
        """
        model = PlanetNatureAllResponse()
        if include_optional:
            return PlanetNatureAllResponse(
                planets = {
                    'key' : asterwise.models.planet_nature_entry.PlanetNatureEntry(
                        tattva = '', 
                        guna = '', 
                        gender = '', 
                        caste = '', 
                        nature = '', 
                        direction = '', 
                        color = '', 
                        deity = '', 
                        day = '', 
                        metal = '', 
                        body_part = '', 
                        friends = [
                            ''
                            ], 
                        enemies = [
                            ''
                            ], 
                        neutrals = [
                            ''
                            ], )
                    }
            )
        else:
            return PlanetNatureAllResponse(
                planets = {
                    'key' : asterwise.models.planet_nature_entry.PlanetNatureEntry(
                        tattva = '', 
                        guna = '', 
                        gender = '', 
                        caste = '', 
                        nature = '', 
                        direction = '', 
                        color = '', 
                        deity = '', 
                        day = '', 
                        metal = '', 
                        body_part = '', 
                        friends = [
                            ''
                            ], 
                        enemies = [
                            ''
                            ], 
                        neutrals = [
                            ''
                            ], )
                    },
        )
        """

    def testPlanetNatureAllResponse(self):
        """Test PlanetNatureAllResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
