# coding: utf-8

"""
    Asterwise API

    Vedic astrology, numerology, horoscope, and PDF report API. Send birth data, get accurate sidereal calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asterwise.models.api_response_tarot_card_schema import ApiResponseTarotCardSchema

class TestApiResponseTarotCardSchema(unittest.TestCase):
    """ApiResponseTarotCardSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiResponseTarotCardSchema:
        """Test ApiResponseTarotCardSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiResponseTarotCardSchema`
        """
        model = ApiResponseTarotCardSchema()
        if include_optional:
            return ApiResponseTarotCardSchema(
                success = True,
                message = 'success',
                data = asterwise.models.tarot_card_schema.TarotCardSchema(
                    id = '', 
                    name = '', 
                    arcana_type = '', 
                    suit = '', 
                    number = 56, 
                    element = '', 
                    astrology_correspondence = '', 
                    keywords_upright = [
                        ''
                        ], 
                    keywords_reversed = [
                        ''
                        ], 
                    upright_meaning = '', 
                    reversed_meaning = '', 
                    yes_no = '', 
                    description = '', )
            )
        else:
            return ApiResponseTarotCardSchema(
                data = asterwise.models.tarot_card_schema.TarotCardSchema(
                    id = '', 
                    name = '', 
                    arcana_type = '', 
                    suit = '', 
                    number = 56, 
                    element = '', 
                    astrology_correspondence = '', 
                    keywords_upright = [
                        ''
                        ], 
                    keywords_reversed = [
                        ''
                        ], 
                    upright_meaning = '', 
                    reversed_meaning = '', 
                    yes_no = '', 
                    description = '', ),
        )
        """

    def testApiResponseTarotCardSchema(self):
        """Test ApiResponseTarotCardSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
