# coding: utf-8

"""
    Asterwise API

    Astrology and divination API — Vedic and Western astrology, numerology, tarot, crystals, dreams, and horoscopes. Send birth data, get accurate calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asterwise.models.api_response_chaldean_response import ApiResponseChaldeanResponse

class TestApiResponseChaldeanResponse(unittest.TestCase):
    """ApiResponseChaldeanResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiResponseChaldeanResponse:
        """Test ApiResponseChaldeanResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiResponseChaldeanResponse`
        """
        model = ApiResponseChaldeanResponse()
        if include_optional:
            return ApiResponseChaldeanResponse(
                success = True,
                message = 'success',
                data = asterwise.models.chaldean_response.ChaldeanResponse(
                    system = '', 
                    full_name = '', 
                    birth_date = '', 
                    name_number = asterwise.models.chaldean_number_block.ChaldeanNumberBlock(
                        raw = 56, 
                        reduced = 56, 
                        theme = '', 
                        keywords = [
                            ''
                            ], 
                        interpretation = '', ), 
                    birth_number = asterwise.models.chaldean_number_block.ChaldeanNumberBlock(
                        raw = 56, 
                        reduced = 56, 
                        theme = '', 
                        keywords = [
                            ''
                            ], 
                        interpretation = '', ), 
                    compound_number = , )
            )
        else:
            return ApiResponseChaldeanResponse(
                data = asterwise.models.chaldean_response.ChaldeanResponse(
                    system = '', 
                    full_name = '', 
                    birth_date = '', 
                    name_number = asterwise.models.chaldean_number_block.ChaldeanNumberBlock(
                        raw = 56, 
                        reduced = 56, 
                        theme = '', 
                        keywords = [
                            ''
                            ], 
                        interpretation = '', ), 
                    birth_number = asterwise.models.chaldean_number_block.ChaldeanNumberBlock(
                        raw = 56, 
                        reduced = 56, 
                        theme = '', 
                        keywords = [
                            ''
                            ], 
                        interpretation = '', ), 
                    compound_number = , ),
        )
        """

    def testApiResponseChaldeanResponse(self):
        """Test ApiResponseChaldeanResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
