# coding: utf-8

"""
    Asterwise API

    Vedic astrology, numerology, horoscope, and PDF report API. Send birth data, get accurate sidereal calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asterwise.models.api_response_natal_response import ApiResponseNatalResponse

class TestApiResponseNatalResponse(unittest.TestCase):
    """ApiResponseNatalResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiResponseNatalResponse:
        """Test ApiResponseNatalResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiResponseNatalResponse`
        """
        model = ApiResponseNatalResponse()
        if include_optional:
            return ApiResponseNatalResponse(
                success = True,
                message = 'success',
                data = asterwise.models.natal_response.NatalResponse(
                    planets = [
                        asterwise.models.planet_position.PlanetPosition(
                            planet = '', 
                            sign = '', 
                            sign_num = 0.0, 
                            degree = 1.337, 
                            nakshatra = '', 
                            nakshatra_pada = 1.0, 
                            is_retrograde = True, 
                            is_combust = True, 
                            is_deep_combust = True, 
                            house = 1.0, 
                            rasi_house = 0.0, 
                            bhava_chalit_house = 1.0, 
                            house_system_note = '', )
                        ], 
                    houses = [
                        asterwise.models.house_data.HouseData(
                            house = 1.0, 
                            sign = '', 
                            sign_num = 56, 
                            degree = 1.337, )
                        ], 
                    ascendant = 1.337, 
                    ascendant_sign = '', 
                    ayanamsa_value = 1.337, 
                    ayanamsa_used = '', 
                    birth_time_unknown = True, 
                    fallback_method = '', 
                    interpretation = [
                        { }
                        ], 
                    ascendant_sign_interpretation = { }, 
                    moon_sign = '', 
                    moon_nakshatra = '', 
                    moon_sign_interpretation = { }, 
                    moon_nakshatra_interpretation = , 
                    avakahada = , 
                    bhava_madhya = [
                        asterwise.models.bhava_madhya_entry.BhavaMadhyaEntry(
                            house = 56, 
                            sign = '', 
                            sign_num = 56, 
                            degree = 1.337, )
                        ], 
                    bhava_sandhi = [
                        asterwise.models.bhava_madhya_entry.BhavaMadhyaEntry(
                            house = 56, 
                            sign = '', 
                            sign_num = 56, 
                            degree = 1.337, )
                        ], 
                    graha_drishti = {
                        'key' : {
                            'key' : 56
                            }
                        }, 
                    rashi_drishti = [
                        asterwise.models.rashi_drishti_entry.RashiDrishtiEntry(
                            from_sign = '', 
                            from_sign_num = 56, 
                            to_sign = '', 
                            to_sign_num = 56, )
                        ], 
                    arudha_padas = {
                        'key' : { }
                        }, 
                    upapada_lagna = null, )
            )
        else:
            return ApiResponseNatalResponse(
                data = asterwise.models.natal_response.NatalResponse(
                    planets = [
                        asterwise.models.planet_position.PlanetPosition(
                            planet = '', 
                            sign = '', 
                            sign_num = 0.0, 
                            degree = 1.337, 
                            nakshatra = '', 
                            nakshatra_pada = 1.0, 
                            is_retrograde = True, 
                            is_combust = True, 
                            is_deep_combust = True, 
                            house = 1.0, 
                            rasi_house = 0.0, 
                            bhava_chalit_house = 1.0, 
                            house_system_note = '', )
                        ], 
                    houses = [
                        asterwise.models.house_data.HouseData(
                            house = 1.0, 
                            sign = '', 
                            sign_num = 56, 
                            degree = 1.337, )
                        ], 
                    ascendant = 1.337, 
                    ascendant_sign = '', 
                    ayanamsa_value = 1.337, 
                    ayanamsa_used = '', 
                    birth_time_unknown = True, 
                    fallback_method = '', 
                    interpretation = [
                        { }
                        ], 
                    ascendant_sign_interpretation = { }, 
                    moon_sign = '', 
                    moon_nakshatra = '', 
                    moon_sign_interpretation = { }, 
                    moon_nakshatra_interpretation = , 
                    avakahada = , 
                    bhava_madhya = [
                        asterwise.models.bhava_madhya_entry.BhavaMadhyaEntry(
                            house = 56, 
                            sign = '', 
                            sign_num = 56, 
                            degree = 1.337, )
                        ], 
                    bhava_sandhi = [
                        asterwise.models.bhava_madhya_entry.BhavaMadhyaEntry(
                            house = 56, 
                            sign = '', 
                            sign_num = 56, 
                            degree = 1.337, )
                        ], 
                    graha_drishti = {
                        'key' : {
                            'key' : 56
                            }
                        }, 
                    rashi_drishti = [
                        asterwise.models.rashi_drishti_entry.RashiDrishtiEntry(
                            from_sign = '', 
                            from_sign_num = 56, 
                            to_sign = '', 
                            to_sign_num = 56, )
                        ], 
                    arudha_padas = {
                        'key' : { }
                        }, 
                    upapada_lagna = null, ),
        )
        """

    def testApiResponseNatalResponse(self):
        """Test ApiResponseNatalResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
