# coding: utf-8

"""
    Asterwise API

    Vedic astrology, numerology, horoscope, and PDF report API. Send birth data, get accurate sidereal calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asterwise.models.varshaphal_report_request import VarshaphalReportRequest

class TestVarshaphalReportRequest(unittest.TestCase):
    """VarshaphalReportRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VarshaphalReportRequest:
        """Test VarshaphalReportRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VarshaphalReportRequest`
        """
        model = VarshaphalReportRequest()
        if include_optional:
            return VarshaphalReportRequest(
                location = '',
                name = 'Chart',
                var_date = '',
                time = '',
                latitude = -90.0,
                longitude = -180.0,
                timezone = '',
                ayanamsa = 'lahiri',
                year = 1900.0,
                branding = asterwise.models.branding_params.BrandingParams(
                    brand_name = '', 
                    brand_logo_url = '', 
                    brand_primary_color = '#1a1a2e', 
                    brand_tagline = '', 
                    prepared_by = '', 
                    footer_text = '', 
                    cover_background_color = '#1a1a2e', )
            )
        else:
            return VarshaphalReportRequest(
                var_date = '',
                year = 1900.0,
        )
        """

    def testVarshaphalReportRequest(self):
        """Test VarshaphalReportRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
