# coding: utf-8

"""
    Asterwise API

    Vedic astrology, numerology, horoscope, and PDF report API. Send birth data, get accurate sidereal calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asterwise.models.moon_phase_response import MoonPhaseResponse

class TestMoonPhaseResponse(unittest.TestCase):
    """MoonPhaseResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MoonPhaseResponse:
        """Test MoonPhaseResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MoonPhaseResponse`
        """
        model = MoonPhaseResponse()
        if include_optional:
            return MoonPhaseResponse(
                var_date = '',
                phase_name = '',
                phase_angle = 1.337,
                illumination_pct = 1.337,
                moon_age_days = 1.337,
                moon_longitude = 1.337,
                sun_longitude = 1.337,
                is_waxing = True,
                next_phase_name = '',
                next_phase_date = ''
            )
        else:
            return MoonPhaseResponse(
                var_date = '',
                phase_name = '',
                phase_angle = 1.337,
                illumination_pct = 1.337,
                moon_age_days = 1.337,
                moon_longitude = 1.337,
                sun_longitude = 1.337,
                is_waxing = True,
                next_phase_name = '',
        )
        """

    def testMoonPhaseResponse(self):
        """Test MoonPhaseResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
