# coding: utf-8

"""
    Asterwise API

    Vedic astrology, numerology, horoscope, and PDF report API. Send birth data, get accurate sidereal calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asterwise.models.api_response_matchmaking_response import ApiResponseMatchmakingResponse

class TestApiResponseMatchmakingResponse(unittest.TestCase):
    """ApiResponseMatchmakingResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiResponseMatchmakingResponse:
        """Test ApiResponseMatchmakingResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiResponseMatchmakingResponse`
        """
        model = ApiResponseMatchmakingResponse()
        if include_optional:
            return ApiResponseMatchmakingResponse(
                success = True,
                message = 'success',
                data = asterwise.models.matchmaking_response.MatchmakingResponse(
                    total_score = 1.337, 
                    breakdown = {
                        'key' : 1.337
                        }, 
                    compatibility_level = '', 
                    doshas = { }, 
                    dosha_cancellations = { }, 
                    analysis = { }, 
                    classical_vetoes = { }, 
                    mangal_compatibility = { }, 
                    supplementary_checks = { }, 
                    compatibility_narrative = { }, 
                    birth_time_unknown = True, 
                    fallback_method = '', )
            )
        else:
            return ApiResponseMatchmakingResponse(
                data = asterwise.models.matchmaking_response.MatchmakingResponse(
                    total_score = 1.337, 
                    breakdown = {
                        'key' : 1.337
                        }, 
                    compatibility_level = '', 
                    doshas = { }, 
                    dosha_cancellations = { }, 
                    analysis = { }, 
                    classical_vetoes = { }, 
                    mangal_compatibility = { }, 
                    supplementary_checks = { }, 
                    compatibility_narrative = { }, 
                    birth_time_unknown = True, 
                    fallback_method = '', ),
        )
        """

    def testApiResponseMatchmakingResponse(self):
        """Test ApiResponseMatchmakingResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
