# coding: utf-8

"""
    Asterwise API

    Vedic astrology, numerology, horoscope, and PDF report API. Send birth data, get accurate sidereal calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asterwise.models.api_response_rahu_kaal_response import ApiResponseRahuKaalResponse

class TestApiResponseRahuKaalResponse(unittest.TestCase):
    """ApiResponseRahuKaalResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiResponseRahuKaalResponse:
        """Test ApiResponseRahuKaalResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiResponseRahuKaalResponse`
        """
        model = ApiResponseRahuKaalResponse()
        if include_optional:
            return ApiResponseRahuKaalResponse(
                success = True,
                message = 'success',
                data = asterwise.models.rahu_kaal_response.RahuKaalResponse(
                    date = '', 
                    sunrise = '', 
                    sunset = '', 
                    rahu_kaal = null, 
                    gulika_kaal = null, 
                    yamaganda_kaal = null, )
            )
        else:
            return ApiResponseRahuKaalResponse(
                data = asterwise.models.rahu_kaal_response.RahuKaalResponse(
                    date = '', 
                    sunrise = '', 
                    sunset = '', 
                    rahu_kaal = null, 
                    gulika_kaal = null, 
                    yamaganda_kaal = null, ),
        )
        """

    def testApiResponseRahuKaalResponse(self):
        """Test ApiResponseRahuKaalResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
