# coding: utf-8

"""
    Asterwise API

    Vedic astrology, numerology, horoscope, and PDF report API. Send birth data, get accurate sidereal calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asterwise.models.api_response_lucky_numbers_api_response import ApiResponseLuckyNumbersApiResponse

class TestApiResponseLuckyNumbersApiResponse(unittest.TestCase):
    """ApiResponseLuckyNumbersApiResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiResponseLuckyNumbersApiResponse:
        """Test ApiResponseLuckyNumbersApiResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiResponseLuckyNumbersApiResponse`
        """
        model = ApiResponseLuckyNumbersApiResponse()
        if include_optional:
            return ApiResponseLuckyNumbersApiResponse(
                success = True,
                message = 'success',
                data = asterwise.models.lucky_numbers_api_response.LuckyNumbersApiResponse(
                    lucky_numbers = [
                        56
                        ], 
                    power_number = 56, 
                    date_specific = True, 
                    interpretation = '', )
            )
        else:
            return ApiResponseLuckyNumbersApiResponse(
                data = asterwise.models.lucky_numbers_api_response.LuckyNumbersApiResponse(
                    lucky_numbers = [
                        56
                        ], 
                    power_number = 56, 
                    date_specific = True, 
                    interpretation = '', ),
        )
        """

    def testApiResponseLuckyNumbersApiResponse(self):
        """Test ApiResponseLuckyNumbersApiResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
