# coding: utf-8

"""
    Asterwise API

    Astrology and divination API — Vedic and Western astrology, numerology, tarot, crystals, dreams, and horoscopes. Send birth data, get accurate calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asterwise.models.api_response_saham_response import ApiResponseSahamResponse

class TestApiResponseSahamResponse(unittest.TestCase):
    """ApiResponseSahamResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiResponseSahamResponse:
        """Test ApiResponseSahamResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiResponseSahamResponse`
        """
        model = ApiResponseSahamResponse()
        if include_optional:
            return ApiResponseSahamResponse(
                success = True,
                message = 'success',
                data = asterwise.models.saham_response.SahamResponse(
                    target_year = 56, 
                    ayanamsa = '', 
                    solar_return_utc = '', 
                    is_day_return = True, 
                    varshaphal_ascendant_longitude = 1.337, 
                    total = 56, 
                    sahams = [
                        asterwise.models.saham_entry.SahamEntry(
                            slug = '', 
                            name = '', 
                            theme = '', 
                            longitude = 1.337, 
                            rashi_index = 56, 
                            rashi = '', 
                            degree_in_sign = 1.337, 
                            saham_lord = '', 
                            formula_used = '', )
                        ], )
            )
        else:
            return ApiResponseSahamResponse(
                data = asterwise.models.saham_response.SahamResponse(
                    target_year = 56, 
                    ayanamsa = '', 
                    solar_return_utc = '', 
                    is_day_return = True, 
                    varshaphal_ascendant_longitude = 1.337, 
                    total = 56, 
                    sahams = [
                        asterwise.models.saham_entry.SahamEntry(
                            slug = '', 
                            name = '', 
                            theme = '', 
                            longitude = 1.337, 
                            rashi_index = 56, 
                            rashi = '', 
                            degree_in_sign = 1.337, 
                            saham_lord = '', 
                            formula_used = '', )
                        ], ),
        )
        """

    def testApiResponseSahamResponse(self):
        """Test ApiResponseSahamResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
