# coding: utf-8

"""
    Asterwise API

    Vedic astrology, numerology, horoscope, and PDF report API. Send birth data, get accurate sidereal calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asterwise.models.drawn_card_schema import DrawnCardSchema

class TestDrawnCardSchema(unittest.TestCase):
    """DrawnCardSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DrawnCardSchema:
        """Test DrawnCardSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DrawnCardSchema`
        """
        model = DrawnCardSchema()
        if include_optional:
            return DrawnCardSchema(
                card = asterwise.models.tarot_card_schema.TarotCardSchema(
                    id = '', 
                    name = '', 
                    arcana_type = '', 
                    suit = '', 
                    number = 56, 
                    element = '', 
                    astrology_correspondence = '', 
                    keywords_upright = [
                        ''
                        ], 
                    keywords_reversed = [
                        ''
                        ], 
                    upright_meaning = '', 
                    reversed_meaning = '', 
                    yes_no = '', 
                    description = '', ),
                is_reversed = True,
                position = '',
                position_meaning = '',
                active_meaning = '',
                active_keywords = [
                    ''
                    ]
            )
        else:
            return DrawnCardSchema(
                card = asterwise.models.tarot_card_schema.TarotCardSchema(
                    id = '', 
                    name = '', 
                    arcana_type = '', 
                    suit = '', 
                    number = 56, 
                    element = '', 
                    astrology_correspondence = '', 
                    keywords_upright = [
                        ''
                        ], 
                    keywords_reversed = [
                        ''
                        ], 
                    upright_meaning = '', 
                    reversed_meaning = '', 
                    yes_no = '', 
                    description = '', ),
                is_reversed = True,
                active_meaning = '',
                active_keywords = [
                    ''
                    ],
        )
        """

    def testDrawnCardSchema(self):
        """Test DrawnCardSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
