# coding: utf-8

"""
    Asterwise API

    Astrology and divination API — Vedic and Western astrology, numerology, tarot, crystals, dreams, and horoscopes. Send birth data, get accurate calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asterwise.models.ghatak_tithi import GhatakTithi

class TestGhatakTithi(unittest.TestCase):
    """GhatakTithi unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GhatakTithi:
        """Test GhatakTithi
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GhatakTithi`
        """
        model = GhatakTithi()
        if include_optional:
            return GhatakTithi(
                group = '',
                tithi_numbers = [
                    56
                    ],
                description = ''
            )
        else:
            return GhatakTithi(
                group = '',
                tithi_numbers = [
                    56
                    ],
                description = '',
        )
        """

    def testGhatakTithi(self):
        """Test GhatakTithi"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
