# coding: utf-8

"""
    Asterwise API

    Vedic astrology, numerology, horoscope, and PDF report API. Send birth data, get accurate sidereal calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asterwise.models.house_data import HouseData

class TestHouseData(unittest.TestCase):
    """HouseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HouseData:
        """Test HouseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HouseData`
        """
        model = HouseData()
        if include_optional:
            return HouseData(
                house = 1.0,
                sign = '',
                sign_num = 56,
                degree = 1.337
            )
        else:
            return HouseData(
                house = 1.0,
                sign = '',
                sign_num = 56,
                degree = 1.337,
        )
        """

    def testHouseData(self):
        """Test HouseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
