# coding: utf-8

"""
    Asterwise API

    Astrology and divination API — Vedic and Western astrology, numerology, tarot, crystals, dreams, and horoscopes. Send birth data, get accurate calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asterwise.models.api_response_horoscope_data import ApiResponseHoroscopeData

class TestApiResponseHoroscopeData(unittest.TestCase):
    """ApiResponseHoroscopeData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiResponseHoroscopeData:
        """Test ApiResponseHoroscopeData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiResponseHoroscopeData`
        """
        model = ApiResponseHoroscopeData()
        if include_optional:
            return ApiResponseHoroscopeData(
                success = True,
                message = 'success',
                data = asterwise.models.horoscope_data.HoroscopeData(
                    content = asterwise.models.horoscope_content.HoroscopeContent(
                        headline = '', 
                        narrative = '', 
                        career = '', 
                        money = '', 
                        love = '', 
                        body = '', 
                        remedy = '', 
                        do = [
                            ''
                            ], 
                        avoid = [
                            ''
                            ], 
                        open_loop = '', 
                        peak_day = '', 
                        caution_day = '', 
                        weekly_mantra = '', 
                        phases = [
                            asterwise.models.horoscope_phase.HoroscopePhase(
                                phase_number = 56, 
                                start_date = '', 
                                end_date = '', 
                                title = '', 
                                narrative = '', )
                            ], 
                        power_window = '', 
                        caution_window = '', 
                        closing_message = '', 
                        year_theme = '', 
                        chapters = [
                            asterwise.models.horoscope_chapter.HoroscopeChapter(
                                chapter_number = 56, 
                                start_date = '', 
                                end_date = '', 
                                title = '', 
                                theme = '', 
                                narrative = '', )
                            ], 
                        auspicious_months = [
                            ''
                            ], 
                        landmark_dates = [
                            asterwise.models.horoscope_landmark_date.HoroscopeLandmarkDate(
                                date = '', 
                                event = '', 
                                tone = '', )
                            ], ), 
                    generated_at = '', 
                    period_key = '', 
                    horizon = '', 
                    moon_sign = '', )
            )
        else:
            return ApiResponseHoroscopeData(
                data = asterwise.models.horoscope_data.HoroscopeData(
                    content = asterwise.models.horoscope_content.HoroscopeContent(
                        headline = '', 
                        narrative = '', 
                        career = '', 
                        money = '', 
                        love = '', 
                        body = '', 
                        remedy = '', 
                        do = [
                            ''
                            ], 
                        avoid = [
                            ''
                            ], 
                        open_loop = '', 
                        peak_day = '', 
                        caution_day = '', 
                        weekly_mantra = '', 
                        phases = [
                            asterwise.models.horoscope_phase.HoroscopePhase(
                                phase_number = 56, 
                                start_date = '', 
                                end_date = '', 
                                title = '', 
                                narrative = '', )
                            ], 
                        power_window = '', 
                        caution_window = '', 
                        closing_message = '', 
                        year_theme = '', 
                        chapters = [
                            asterwise.models.horoscope_chapter.HoroscopeChapter(
                                chapter_number = 56, 
                                start_date = '', 
                                end_date = '', 
                                title = '', 
                                theme = '', 
                                narrative = '', )
                            ], 
                        auspicious_months = [
                            ''
                            ], 
                        landmark_dates = [
                            asterwise.models.horoscope_landmark_date.HoroscopeLandmarkDate(
                                date = '', 
                                event = '', 
                                tone = '', )
                            ], ), 
                    generated_at = '', 
                    period_key = '', 
                    horizon = '', 
                    moon_sign = '', ),
        )
        """

    def testApiResponseHoroscopeData(self):
        """Test ApiResponseHoroscopeData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
