# coding: utf-8

"""
    Asterwise API

    Vedic astrology, numerology, horoscope, and PDF report API. Send birth data, get accurate sidereal calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asterwise.models.api_response_number_meaning_response import ApiResponseNumberMeaningResponse

class TestApiResponseNumberMeaningResponse(unittest.TestCase):
    """ApiResponseNumberMeaningResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiResponseNumberMeaningResponse:
        """Test ApiResponseNumberMeaningResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiResponseNumberMeaningResponse`
        """
        model = ApiResponseNumberMeaningResponse()
        if include_optional:
            return ApiResponseNumberMeaningResponse(
                success = True,
                message = 'success',
                data = asterwise.models.number_meaning_response.NumberMeaningResponse(
                    number = 56, 
                    context = 'general', 
                    interpretation = '', 
                    keywords = [
                        ''
                        ], 
                    theme = '', 
                    opportunities = [
                        ''
                        ], 
                    challenges = [
                        ''
                        ], 
                    advice = '', )
            )
        else:
            return ApiResponseNumberMeaningResponse(
                data = asterwise.models.number_meaning_response.NumberMeaningResponse(
                    number = 56, 
                    context = 'general', 
                    interpretation = '', 
                    keywords = [
                        ''
                        ], 
                    theme = '', 
                    opportunities = [
                        ''
                        ], 
                    challenges = [
                        ''
                        ], 
                    advice = '', ),
        )
        """

    def testApiResponseNumberMeaningResponse(self):
        """Test ApiResponseNumberMeaningResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
