# coding: utf-8

"""
    Asterwise API

    Vedic astrology, numerology, horoscope, and PDF report API. Send birth data, get accurate sidereal calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asterwise.models.solar_arc_planet_schema import SolarArcPlanetSchema

class TestSolarArcPlanetSchema(unittest.TestCase):
    """SolarArcPlanetSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SolarArcPlanetSchema:
        """Test SolarArcPlanetSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SolarArcPlanetSchema`
        """
        model = SolarArcPlanetSchema()
        if include_optional:
            return SolarArcPlanetSchema(
                name = '',
                natal_longitude = 1.337,
                directed_longitude = 1.337,
                sign = '',
                sign_index = 56,
                degree_in_sign = 1.337,
                dignity = '',
                dignity_score = 56
            )
        else:
            return SolarArcPlanetSchema(
                name = '',
                natal_longitude = 1.337,
                directed_longitude = 1.337,
                sign = '',
                sign_index = 56,
                degree_in_sign = 1.337,
                dignity = '',
                dignity_score = 56,
        )
        """

    def testSolarArcPlanetSchema(self):
        """Test SolarArcPlanetSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
