# coding: utf-8

"""
    Asterwise API

    Vedic astrology, numerology, horoscope, and PDF report API. Send birth data, get accurate sidereal calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AshtakavargaResponse(BaseModel):
    """
    AshtakavargaResponse
    """ # noqa: E501
    bhinna: Dict[str, Dict[str, StrictInt]] = Field(description="Bhinna Ashtakavarga (BAV) for each planet plus Lagna. Keys: Sun, Moon, Mars, Mercury, Jupiter, Venus, Saturn, Lagna. Each value maps Sanskrit sign name (Mesha…Meena) to bindu count for that sign.")
    bhinna_after_trikona: Dict[str, Dict[str, StrictInt]] = Field(description="BAV after Trikona Shodana (triangular reduction). Keys: Sun, Moon, Mars, Mercury, Jupiter, Venus, Saturn. Each value maps Sanskrit sign name to bindu count.")
    bhinna_after_ekadhipatya: Dict[str, Dict[str, StrictInt]] = Field(description="BAV after both Trikona and Ekadhipatya Shodana (lordship reduction). Keys: Sun, Moon, Mars, Mercury, Jupiter, Venus, Saturn. Each value maps Sanskrit sign name to bindu count. This is the most refined per-planet Ashtakavarga.")
    sarva: Dict[str, StrictInt] = Field(description="Sarva Ashtakavarga (SAV) — the raw sum of all 7 planet BAVs across 12 signs. Keys: Mesha through Meena.")
    sarva_reduced: Dict[str, StrictInt] = Field(description="Reduced SAV — sum of the 7 fully reduced planet BAVs (after both Trikona and Ekadhipatya Shodana). Keys: Mesha through Meena. More accurate than sarva for predictive work.")
    after_trikona: Dict[str, StrictInt] = Field(description="SAV after Trikona Shodana applied directly to the raw SAV. Keys: Mesha through Meena.")
    after_ekadhipatya: Dict[str, StrictInt] = Field(description="SAV after both Trikona and Ekadhipatya Shodana applied directly to the raw SAV. Keys: Mesha through Meena.")
    birth_time_unknown: Optional[StrictBool] = Field(default=False, description="Whether birth time fallback was used")
    fallback_method: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["bhinna", "bhinna_after_trikona", "bhinna_after_ekadhipatya", "sarva", "sarva_reduced", "after_trikona", "after_ekadhipatya", "birth_time_unknown", "fallback_method"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AshtakavargaResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if fallback_method (nullable) is None
        # and model_fields_set contains the field
        if self.fallback_method is None and "fallback_method" in self.model_fields_set:
            _dict['fallback_method'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AshtakavargaResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bhinna": obj.get("bhinna"),
            "bhinna_after_trikona": obj.get("bhinna_after_trikona"),
            "bhinna_after_ekadhipatya": obj.get("bhinna_after_ekadhipatya"),
            "sarva": obj.get("sarva"),
            "sarva_reduced": obj.get("sarva_reduced"),
            "after_trikona": obj.get("after_trikona"),
            "after_ekadhipatya": obj.get("after_ekadhipatya"),
            "birth_time_unknown": obj.get("birth_time_unknown") if obj.get("birth_time_unknown") is not None else False,
            "fallback_method": obj.get("fallback_method")
        })
        return _obj


