# coding: utf-8

"""
    Asterwise API

    Astrology and divination API — Vedic and Western astrology, numerology, tarot, crystals, dreams, and horoscopes. Send birth data, get accurate calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BirthMoment(BaseModel):
    """
    BirthMoment
    """ # noqa: E501
    utc: StrictStr = Field(description="The birth instant the chart was computed for, in UTC (ISO 8601, to the second).")
    utc_offset: StrictStr = Field(description="UTC offset applied to the local birth time, as ±HH:MM or ±HH:MM:SS.")
    offset_basis: StrictStr = Field(description="Where the offset came from: the IANA time zone; the birthplace's local mean time (longitude / 15 hours), used for dates before the zone adopted a standard time; or the explicit utc_offset input.")
    local_time_status: StrictStr = Field(description="'nonexistent': the local time fell in a daylight-saving gap and was read with the offset in force before the change (moved forward by the gap). 'ambiguous': the local time occurred twice and the first occurrence was used. 'ok' otherwise.")
    __properties: ClassVar[List[str]] = ["utc", "utc_offset", "offset_basis", "local_time_status"]

    @field_validator('offset_basis')
    def offset_basis_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['iana', 'local_mean_time', 'explicit_offset']):
            raise ValueError("must be one of enum values ('iana', 'local_mean_time', 'explicit_offset')")
        return value

    @field_validator('local_time_status')
    def local_time_status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['ok', 'nonexistent', 'ambiguous']):
            raise ValueError("must be one of enum values ('ok', 'nonexistent', 'ambiguous')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BirthMoment from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BirthMoment from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "utc": obj.get("utc"),
            "utc_offset": obj.get("utc_offset"),
            "offset_basis": obj.get("offset_basis"),
            "local_time_status": obj.get("local_time_status")
        })
        return _obj


