# coding: utf-8

"""
    Asterwise API

    Astrology and divination API — Vedic and Western astrology, numerology, tarot, crystals, dreams, and horoscopes. Send birth data, get accurate calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from asterwise.models.bhadra_window import BhadraWindow
from asterwise.models.calendar_karana import CalendarKarana
from asterwise.models.calendar_nakshatra import CalendarNakshatra
from asterwise.models.calendar_rahu_kaal import CalendarRahuKaal
from asterwise.models.calendar_tithi import CalendarTithi
from asterwise.models.calendar_vara import CalendarVara
from asterwise.models.calendar_yoga import CalendarYoga
from asterwise.models.day_karana import DayKarana
from asterwise.models.day_nakshatra import DayNakshatra
from asterwise.models.day_tithi import DayTithi
from asterwise.models.day_yoga import DayYoga
from asterwise.models.masa import Masa
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CalendarDay(BaseModel):
    """
    CalendarDay
    """ # noqa: E501
    var_date: StrictStr = Field(description="Date in YYYY-MM-DD format.", alias="date")
    tithi: CalendarTithi = Field(description="Tithi at sunrise.")
    vara: CalendarVara = Field(description="Weekday for this day.")
    nakshatra: CalendarNakshatra = Field(description="Moon nakshatra at sunrise.")
    yoga: CalendarYoga = Field(description="Yoga at sunrise.")
    karana: CalendarKarana = Field(description="Karana at sunrise.")
    rahu_kaal: CalendarRahuKaal = Field(description="Rahu Kaal window for this day.")
    sunrise: Optional[StrictStr] = None
    sunset: Optional[StrictStr] = None
    moonrise: Optional[StrictStr] = None
    moonset: Optional[StrictStr] = None
    paksha: Optional[StrictStr] = None
    masa: Optional[Masa] = None
    tithis: Optional[List[DayTithi]] = None
    nakshatras: Optional[List[DayNakshatra]] = None
    yogas: Optional[List[DayYoga]] = None
    karanas: Optional[List[DayKarana]] = None
    bhadra: Optional[List[BhadraWindow]] = None
    __properties: ClassVar[List[str]] = ["date", "tithi", "vara", "nakshatra", "yoga", "karana", "rahu_kaal", "sunrise", "sunset", "moonrise", "moonset", "paksha", "masa", "tithis", "nakshatras", "yogas", "karanas", "bhadra"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CalendarDay from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of tithi
        if self.tithi:
            _dict['tithi'] = self.tithi.to_dict()
        # override the default output from pydantic by calling `to_dict()` of vara
        if self.vara:
            _dict['vara'] = self.vara.to_dict()
        # override the default output from pydantic by calling `to_dict()` of nakshatra
        if self.nakshatra:
            _dict['nakshatra'] = self.nakshatra.to_dict()
        # override the default output from pydantic by calling `to_dict()` of yoga
        if self.yoga:
            _dict['yoga'] = self.yoga.to_dict()
        # override the default output from pydantic by calling `to_dict()` of karana
        if self.karana:
            _dict['karana'] = self.karana.to_dict()
        # override the default output from pydantic by calling `to_dict()` of rahu_kaal
        if self.rahu_kaal:
            _dict['rahu_kaal'] = self.rahu_kaal.to_dict()
        # override the default output from pydantic by calling `to_dict()` of masa
        if self.masa:
            _dict['masa'] = self.masa.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in tithis (list)
        _items = []
        if self.tithis:
            for _item_tithis in self.tithis:
                if _item_tithis:
                    _items.append(_item_tithis.to_dict())
            _dict['tithis'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in nakshatras (list)
        _items = []
        if self.nakshatras:
            for _item_nakshatras in self.nakshatras:
                if _item_nakshatras:
                    _items.append(_item_nakshatras.to_dict())
            _dict['nakshatras'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in yogas (list)
        _items = []
        if self.yogas:
            for _item_yogas in self.yogas:
                if _item_yogas:
                    _items.append(_item_yogas.to_dict())
            _dict['yogas'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in karanas (list)
        _items = []
        if self.karanas:
            for _item_karanas in self.karanas:
                if _item_karanas:
                    _items.append(_item_karanas.to_dict())
            _dict['karanas'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in bhadra (list)
        _items = []
        if self.bhadra:
            for _item_bhadra in self.bhadra:
                if _item_bhadra:
                    _items.append(_item_bhadra.to_dict())
            _dict['bhadra'] = _items
        # set to None if sunrise (nullable) is None
        # and model_fields_set contains the field
        if self.sunrise is None and "sunrise" in self.model_fields_set:
            _dict['sunrise'] = None

        # set to None if sunset (nullable) is None
        # and model_fields_set contains the field
        if self.sunset is None and "sunset" in self.model_fields_set:
            _dict['sunset'] = None

        # set to None if moonrise (nullable) is None
        # and model_fields_set contains the field
        if self.moonrise is None and "moonrise" in self.model_fields_set:
            _dict['moonrise'] = None

        # set to None if moonset (nullable) is None
        # and model_fields_set contains the field
        if self.moonset is None and "moonset" in self.model_fields_set:
            _dict['moonset'] = None

        # set to None if paksha (nullable) is None
        # and model_fields_set contains the field
        if self.paksha is None and "paksha" in self.model_fields_set:
            _dict['paksha'] = None

        # set to None if masa (nullable) is None
        # and model_fields_set contains the field
        if self.masa is None and "masa" in self.model_fields_set:
            _dict['masa'] = None

        # set to None if tithis (nullable) is None
        # and model_fields_set contains the field
        if self.tithis is None and "tithis" in self.model_fields_set:
            _dict['tithis'] = None

        # set to None if nakshatras (nullable) is None
        # and model_fields_set contains the field
        if self.nakshatras is None and "nakshatras" in self.model_fields_set:
            _dict['nakshatras'] = None

        # set to None if yogas (nullable) is None
        # and model_fields_set contains the field
        if self.yogas is None and "yogas" in self.model_fields_set:
            _dict['yogas'] = None

        # set to None if karanas (nullable) is None
        # and model_fields_set contains the field
        if self.karanas is None and "karanas" in self.model_fields_set:
            _dict['karanas'] = None

        # set to None if bhadra (nullable) is None
        # and model_fields_set contains the field
        if self.bhadra is None and "bhadra" in self.model_fields_set:
            _dict['bhadra'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CalendarDay from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "date": obj.get("date"),
            "tithi": CalendarTithi.from_dict(obj["tithi"]) if obj.get("tithi") is not None else None,
            "vara": CalendarVara.from_dict(obj["vara"]) if obj.get("vara") is not None else None,
            "nakshatra": CalendarNakshatra.from_dict(obj["nakshatra"]) if obj.get("nakshatra") is not None else None,
            "yoga": CalendarYoga.from_dict(obj["yoga"]) if obj.get("yoga") is not None else None,
            "karana": CalendarKarana.from_dict(obj["karana"]) if obj.get("karana") is not None else None,
            "rahu_kaal": CalendarRahuKaal.from_dict(obj["rahu_kaal"]) if obj.get("rahu_kaal") is not None else None,
            "sunrise": obj.get("sunrise"),
            "sunset": obj.get("sunset"),
            "moonrise": obj.get("moonrise"),
            "moonset": obj.get("moonset"),
            "paksha": obj.get("paksha"),
            "masa": Masa.from_dict(obj["masa"]) if obj.get("masa") is not None else None,
            "tithis": [DayTithi.from_dict(_item) for _item in obj["tithis"]] if obj.get("tithis") is not None else None,
            "nakshatras": [DayNakshatra.from_dict(_item) for _item in obj["nakshatras"]] if obj.get("nakshatras") is not None else None,
            "yogas": [DayYoga.from_dict(_item) for _item in obj["yogas"]] if obj.get("yogas") is not None else None,
            "karanas": [DayKarana.from_dict(_item) for _item in obj["karanas"]] if obj.get("karanas") is not None else None,
            "bhadra": [BhadraWindow.from_dict(_item) for _item in obj["bhadra"]] if obj.get("bhadra") is not None else None
        })
        return _obj


