# coding: utf-8

"""
    Asterwise API

    Astrology and divination API — Vedic and Western astrology, numerology, tarot, crystals, dreams, and horoscopes. Send birth data, get accurate calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from asterwise.models.rudraksha_all_response import RudrakshaAllResponse
from asterwise.models.rudraksha_single_response import RudrakshaSingleResponse
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

DATA3_ANY_OF_SCHEMAS = ["RudrakshaAllResponse", "RudrakshaSingleResponse"]

class Data3(BaseModel):
    """
    The endpoint response payload
    """

    # data type: RudrakshaAllResponse
    anyof_schema_1_validator: Optional[RudrakshaAllResponse] = None
    # data type: RudrakshaSingleResponse
    anyof_schema_2_validator: Optional[RudrakshaSingleResponse] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[RudrakshaAllResponse, RudrakshaSingleResponse]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "RudrakshaAllResponse", "RudrakshaSingleResponse" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = Data3.model_construct()
        error_messages = []
        # validate data type: RudrakshaAllResponse
        if not isinstance(v, RudrakshaAllResponse):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RudrakshaAllResponse`")
        else:
            return v

        # validate data type: RudrakshaSingleResponse
        if not isinstance(v, RudrakshaSingleResponse):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RudrakshaSingleResponse`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in Data3 with anyOf schemas: RudrakshaAllResponse, RudrakshaSingleResponse. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[RudrakshaAllResponse] = None
        try:
            instance.actual_instance = RudrakshaAllResponse.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[RudrakshaSingleResponse] = None
        try:
            instance.actual_instance = RudrakshaSingleResponse.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into Data3 with anyOf schemas: RudrakshaAllResponse, RudrakshaSingleResponse. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], RudrakshaAllResponse, RudrakshaSingleResponse]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


