# coding: utf-8

"""
    Asterwise API

    Astrology and divination API — Vedic and Western astrology, numerology, tarot, crystals, dreams, and horoscopes. Send birth data, get accurate calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DayKarana(BaseModel):
    """
    DayKarana
    """ # noqa: E501
    at_sunrise: StrictBool = Field(description="True for the limb running at this day's sunrise (the one a printed panchang names for the day).")
    is_kshaya: StrictBool = Field(description="Starts after this sunrise and ends before the next, so no sunrise falls in it.")
    is_vriddhi: StrictBool = Field(description="Runs through two consecutive sunrises, so it is the sunrise limb of two days (flagged on both).")
    start: StrictStr = Field(description="Start. ISO 8601 local time with UTC offset, e.g. 2026-11-06T10:31:09+05:30.")
    end: StrictStr = Field(description="End. ISO 8601 local time with UTC offset, e.g. 2026-11-06T10:31:09+05:30.")
    number: StrictInt = Field(description="1 to 60 within the lunar month.")
    name: StrictStr
    lord: Optional[StrictStr] = None
    is_vishti: StrictBool = Field(description="Vishti karana, also called Bhadra.")
    __properties: ClassVar[List[str]] = ["at_sunrise", "is_kshaya", "is_vriddhi", "start", "end", "number", "name", "lord", "is_vishti"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DayKarana from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if lord (nullable) is None
        # and model_fields_set contains the field
        if self.lord is None and "lord" in self.model_fields_set:
            _dict['lord'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DayKarana from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "at_sunrise": obj.get("at_sunrise"),
            "is_kshaya": obj.get("is_kshaya"),
            "is_vriddhi": obj.get("is_vriddhi"),
            "start": obj.get("start"),
            "end": obj.get("end"),
            "number": obj.get("number"),
            "name": obj.get("name"),
            "lord": obj.get("lord"),
            "is_vishti": obj.get("is_vishti")
        })
        return _obj


