# coding: utf-8

"""
    Asterwise API

    Astrology and divination API — Vedic and Western astrology, numerology, tarot, crystals, dreams, and horoscopes. Send birth data, get accurate calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from asterwise.models.bhadra_window import BhadraWindow
from asterwise.models.day_parts import DayParts
from asterwise.models.nakshatra_window import NakshatraWindow
from asterwise.models.time_window import TimeWindow
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DayTimings(BaseModel):
    """
    DayTimings
    """ # noqa: E501
    brahma_muhurta: TimeWindow = Field(description="14th muhurta of the preceding night.")
    pratah_sandhya: TimeWindow
    abhijit: Optional[TimeWindow] = None
    vijaya_muhurta: TimeWindow
    godhuli_muhurta: TimeWindow
    sayahna_sandhya: TimeWindow
    nishita_muhurta: TimeWindow = Field(description="8th night muhurta (around local midnight).")
    madhyahna: StrictStr = Field(description="Local apparent noon. ISO 8601 local time with UTC offset, e.g. 2026-11-06T10:31:09+05:30.")
    pradosh: TimeWindow = Field(description="First three muhurtas of the night (one fifth of it).")
    rahu_kaal: TimeWindow
    gulika_kaal: TimeWindow
    yamaganda_kaal: TimeWindow
    durmuhurta: List[TimeWindow]
    varjyam: List[NakshatraWindow] = Field(description="Windows beginning this day (4 ghatis of the nakshatra).")
    amrit_kaal: List[NakshatraWindow] = Field(description="Windows beginning this day (4 ghatis of the nakshatra).")
    bhadra: List[BhadraWindow] = Field(description="Vishti karana during the day, split where the Moon changes sign.")
    panchaka: List[TimeWindow] = Field(description="Moon in Kumbha or Meena (Dhanishtha pada 3 to Revati).")
    day_parts: DayParts = Field(description="The day in five equal parts, used for festival timing.")
    __properties: ClassVar[List[str]] = ["brahma_muhurta", "pratah_sandhya", "abhijit", "vijaya_muhurta", "godhuli_muhurta", "sayahna_sandhya", "nishita_muhurta", "madhyahna", "pradosh", "rahu_kaal", "gulika_kaal", "yamaganda_kaal", "durmuhurta", "varjyam", "amrit_kaal", "bhadra", "panchaka", "day_parts"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DayTimings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of brahma_muhurta
        if self.brahma_muhurta:
            _dict['brahma_muhurta'] = self.brahma_muhurta.to_dict()
        # override the default output from pydantic by calling `to_dict()` of pratah_sandhya
        if self.pratah_sandhya:
            _dict['pratah_sandhya'] = self.pratah_sandhya.to_dict()
        # override the default output from pydantic by calling `to_dict()` of abhijit
        if self.abhijit:
            _dict['abhijit'] = self.abhijit.to_dict()
        # override the default output from pydantic by calling `to_dict()` of vijaya_muhurta
        if self.vijaya_muhurta:
            _dict['vijaya_muhurta'] = self.vijaya_muhurta.to_dict()
        # override the default output from pydantic by calling `to_dict()` of godhuli_muhurta
        if self.godhuli_muhurta:
            _dict['godhuli_muhurta'] = self.godhuli_muhurta.to_dict()
        # override the default output from pydantic by calling `to_dict()` of sayahna_sandhya
        if self.sayahna_sandhya:
            _dict['sayahna_sandhya'] = self.sayahna_sandhya.to_dict()
        # override the default output from pydantic by calling `to_dict()` of nishita_muhurta
        if self.nishita_muhurta:
            _dict['nishita_muhurta'] = self.nishita_muhurta.to_dict()
        # override the default output from pydantic by calling `to_dict()` of pradosh
        if self.pradosh:
            _dict['pradosh'] = self.pradosh.to_dict()
        # override the default output from pydantic by calling `to_dict()` of rahu_kaal
        if self.rahu_kaal:
            _dict['rahu_kaal'] = self.rahu_kaal.to_dict()
        # override the default output from pydantic by calling `to_dict()` of gulika_kaal
        if self.gulika_kaal:
            _dict['gulika_kaal'] = self.gulika_kaal.to_dict()
        # override the default output from pydantic by calling `to_dict()` of yamaganda_kaal
        if self.yamaganda_kaal:
            _dict['yamaganda_kaal'] = self.yamaganda_kaal.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in durmuhurta (list)
        _items = []
        if self.durmuhurta:
            for _item_durmuhurta in self.durmuhurta:
                if _item_durmuhurta:
                    _items.append(_item_durmuhurta.to_dict())
            _dict['durmuhurta'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in varjyam (list)
        _items = []
        if self.varjyam:
            for _item_varjyam in self.varjyam:
                if _item_varjyam:
                    _items.append(_item_varjyam.to_dict())
            _dict['varjyam'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in amrit_kaal (list)
        _items = []
        if self.amrit_kaal:
            for _item_amrit_kaal in self.amrit_kaal:
                if _item_amrit_kaal:
                    _items.append(_item_amrit_kaal.to_dict())
            _dict['amrit_kaal'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in bhadra (list)
        _items = []
        if self.bhadra:
            for _item_bhadra in self.bhadra:
                if _item_bhadra:
                    _items.append(_item_bhadra.to_dict())
            _dict['bhadra'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in panchaka (list)
        _items = []
        if self.panchaka:
            for _item_panchaka in self.panchaka:
                if _item_panchaka:
                    _items.append(_item_panchaka.to_dict())
            _dict['panchaka'] = _items
        # override the default output from pydantic by calling `to_dict()` of day_parts
        if self.day_parts:
            _dict['day_parts'] = self.day_parts.to_dict()
        # set to None if abhijit (nullable) is None
        # and model_fields_set contains the field
        if self.abhijit is None and "abhijit" in self.model_fields_set:
            _dict['abhijit'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DayTimings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "brahma_muhurta": TimeWindow.from_dict(obj["brahma_muhurta"]) if obj.get("brahma_muhurta") is not None else None,
            "pratah_sandhya": TimeWindow.from_dict(obj["pratah_sandhya"]) if obj.get("pratah_sandhya") is not None else None,
            "abhijit": TimeWindow.from_dict(obj["abhijit"]) if obj.get("abhijit") is not None else None,
            "vijaya_muhurta": TimeWindow.from_dict(obj["vijaya_muhurta"]) if obj.get("vijaya_muhurta") is not None else None,
            "godhuli_muhurta": TimeWindow.from_dict(obj["godhuli_muhurta"]) if obj.get("godhuli_muhurta") is not None else None,
            "sayahna_sandhya": TimeWindow.from_dict(obj["sayahna_sandhya"]) if obj.get("sayahna_sandhya") is not None else None,
            "nishita_muhurta": TimeWindow.from_dict(obj["nishita_muhurta"]) if obj.get("nishita_muhurta") is not None else None,
            "madhyahna": obj.get("madhyahna"),
            "pradosh": TimeWindow.from_dict(obj["pradosh"]) if obj.get("pradosh") is not None else None,
            "rahu_kaal": TimeWindow.from_dict(obj["rahu_kaal"]) if obj.get("rahu_kaal") is not None else None,
            "gulika_kaal": TimeWindow.from_dict(obj["gulika_kaal"]) if obj.get("gulika_kaal") is not None else None,
            "yamaganda_kaal": TimeWindow.from_dict(obj["yamaganda_kaal"]) if obj.get("yamaganda_kaal") is not None else None,
            "durmuhurta": [TimeWindow.from_dict(_item) for _item in obj["durmuhurta"]] if obj.get("durmuhurta") is not None else None,
            "varjyam": [NakshatraWindow.from_dict(_item) for _item in obj["varjyam"]] if obj.get("varjyam") is not None else None,
            "amrit_kaal": [NakshatraWindow.from_dict(_item) for _item in obj["amrit_kaal"]] if obj.get("amrit_kaal") is not None else None,
            "bhadra": [BhadraWindow.from_dict(_item) for _item in obj["bhadra"]] if obj.get("bhadra") is not None else None,
            "panchaka": [TimeWindow.from_dict(_item) for _item in obj["panchaka"]] if obj.get("panchaka") is not None else None,
            "day_parts": DayParts.from_dict(obj["day_parts"]) if obj.get("day_parts") is not None else None
        })
        return _obj


