# coding: utf-8

"""
    Asterwise API

    Astrology and divination API — Vedic and Western astrology, numerology, tarot, crystals, dreams, and horoscopes. Send birth data, get accurate calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DigitNumberAnalysisResponse(BaseModel):
    """
    Mobile or vehicle number analysis (digit-sum reduction).
    """ # noqa: E501
    input: StrictStr
    input_type: StrictStr
    total: StrictInt = Field(description="Sum of the digits in digits_used")
    single_digit: StrictInt = Field(description="Total reduced to 1-9 (master totals reduce too, e.g. 11 → 2)")
    is_master: StrictBool = Field(description="True when the total, or a step of its reduction, is 11, 22 or 33")
    master_number: Optional[StrictInt] = None
    digits_used: Optional[StrictStr] = None
    country_code: Optional[StrictInt] = None
    theme: StrictStr
    favourable_for: List[StrictStr]
    caution: StrictStr
    harmony_score: StrictInt
    __properties: ClassVar[List[str]] = ["input", "input_type", "total", "single_digit", "is_master", "master_number", "digits_used", "country_code", "theme", "favourable_for", "caution", "harmony_score"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DigitNumberAnalysisResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if master_number (nullable) is None
        # and model_fields_set contains the field
        if self.master_number is None and "master_number" in self.model_fields_set:
            _dict['master_number'] = None

        # set to None if digits_used (nullable) is None
        # and model_fields_set contains the field
        if self.digits_used is None and "digits_used" in self.model_fields_set:
            _dict['digits_used'] = None

        # set to None if country_code (nullable) is None
        # and model_fields_set contains the field
        if self.country_code is None and "country_code" in self.model_fields_set:
            _dict['country_code'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DigitNumberAnalysisResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "input": obj.get("input"),
            "input_type": obj.get("input_type"),
            "total": obj.get("total"),
            "single_digit": obj.get("single_digit"),
            "is_master": obj.get("is_master"),
            "master_number": obj.get("master_number"),
            "digits_used": obj.get("digits_used"),
            "country_code": obj.get("country_code"),
            "theme": obj.get("theme"),
            "favourable_for": obj.get("favourable_for"),
            "caution": obj.get("caution"),
            "harmony_score": obj.get("harmony_score")
        })
        return _obj


