# coding: utf-8

"""
    Asterwise API

    Vedic astrology, numerology, horoscope, and PDF report API. Send birth data, get accurate sidereal calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DivisionalResponse(BaseModel):
    """
    DivisionalResponse
    """ # noqa: E501
    d1: Dict[str, Any] = Field(description="Rashi — the natal chart itself", alias="D1")
    d2: Dict[str, Any] = Field(description="Hora — wealth and financial potential", alias="D2")
    d3: Dict[str, Any] = Field(description="Drekkana — siblings and courage", alias="D3")
    d4: Dict[str, Any] = Field(description="Chaturthamsha — property and fixed assets", alias="D4")
    d7: Dict[str, Any] = Field(description="Saptamsha — children and creative output", alias="D7")
    d9: Dict[str, Any] = Field(description="Navamsha — spouse, dharma, and deeper soul purpose. The most important divisional chart.", alias="D9")
    d10: Dict[str, Any] = Field(description="Dashamsha — career and professional life", alias="D10")
    d12: Dict[str, Any] = Field(description="Dwadashamsha — parents and ancestral karma", alias="D12")
    d16: Dict[str, Any] = Field(description="Shodashamsha — vehicles and comforts", alias="D16")
    d20: Dict[str, Any] = Field(description="Vimshamsha — spiritual life and upasana", alias="D20")
    d24: Dict[str, Any] = Field(description="Chaturvimshamsha — education and learning", alias="D24")
    d27: Dict[str, Any] = Field(description="Bhamsha — strength and physical vitality", alias="D27")
    d30: Dict[str, Any] = Field(description="Trimshamsha — misfortunes and evils", alias="D30")
    d40: Dict[str, Any] = Field(description="Khavedamsha — auspicious and inauspicious effects", alias="D40")
    d45: Dict[str, Any] = Field(description="Akshavedamsha — all matters of life", alias="D45")
    d60: Dict[str, Any] = Field(description="Shashtyamsha — all matters, most subtle divisional chart", alias="D60")
    birth_time_unknown: Optional[StrictBool] = Field(default=False, description="True if birth time was unknown and sunrise was used.")
    fallback_method: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["D1", "D2", "D3", "D4", "D7", "D9", "D10", "D12", "D16", "D20", "D24", "D27", "D30", "D40", "D45", "D60", "birth_time_unknown", "fallback_method"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DivisionalResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if fallback_method (nullable) is None
        # and model_fields_set contains the field
        if self.fallback_method is None and "fallback_method" in self.model_fields_set:
            _dict['fallback_method'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DivisionalResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "D1": obj.get("D1"),
            "D2": obj.get("D2"),
            "D3": obj.get("D3"),
            "D4": obj.get("D4"),
            "D7": obj.get("D7"),
            "D9": obj.get("D9"),
            "D10": obj.get("D10"),
            "D12": obj.get("D12"),
            "D16": obj.get("D16"),
            "D20": obj.get("D20"),
            "D24": obj.get("D24"),
            "D27": obj.get("D27"),
            "D30": obj.get("D30"),
            "D40": obj.get("D40"),
            "D45": obj.get("D45"),
            "D60": obj.get("D60"),
            "birth_time_unknown": obj.get("birth_time_unknown") if obj.get("birth_time_unknown") is not None else False,
            "fallback_method": obj.get("fallback_method")
        })
        return _obj


