# coding: utf-8

"""
    Asterwise API

    Vedic astrology, numerology, horoscope, and PDF report API. Send birth data, get accurate sidereal calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ErrorResponse(BaseModel):
    """
    Standard error envelope returned by all Asterwise API endpoints.  Every error response follows this 8-field shape. The 'error' field is the machine-readable identifier (use it for programmatic handling). The 'message' field is the human-readable explanation. The 'doc_url' field links to the canonical documentation for the error code. Include 'request_id' when contacting support.
    """ # noqa: E501
    success: Optional[StrictBool] = Field(default=False, description="Always false for error responses.")
    error: StrictStr = Field(description="Machine-readable error code. Use this for programmatic error handling. See doc_url for the canonical docs page.")
    message: StrictStr = Field(description="Human-readable explanation of what went wrong and how to fix it. Safe to surface in customer-facing UIs.")
    details: Optional[List[Any]] = Field(default=None, description="Optional structured details. For validation errors, contains per-field error objects. Empty list when there are no structured details.")
    retry_after: Optional[StrictInt] = None
    doc_url: StrictStr = Field(description="Canonical documentation URL for this error code. Contains causes, examples, and resolution steps.")
    request_id: Optional[StrictStr] = None
    timestamp: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["success", "error", "message", "details", "retry_after", "doc_url", "request_id", "timestamp"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ErrorResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if retry_after (nullable) is None
        # and model_fields_set contains the field
        if self.retry_after is None and "retry_after" in self.model_fields_set:
            _dict['retry_after'] = None

        # set to None if request_id (nullable) is None
        # and model_fields_set contains the field
        if self.request_id is None and "request_id" in self.model_fields_set:
            _dict['request_id'] = None

        # set to None if timestamp (nullable) is None
        # and model_fields_set contains the field
        if self.timestamp is None and "timestamp" in self.model_fields_set:
            _dict['timestamp'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ErrorResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "success": obj.get("success") if obj.get("success") is not None else False,
            "error": obj.get("error"),
            "message": obj.get("message"),
            "details": obj.get("details"),
            "retry_after": obj.get("retry_after"),
            "doc_url": obj.get("doc_url"),
            "request_id": obj.get("request_id"),
            "timestamp": obj.get("timestamp")
        })
        return _obj


