# coding: utf-8

"""
    Asterwise API

    Astrology and divination API — Vedic and Western astrology, numerology, tarot, crystals, dreams, and horoscopes. Send birth data, get accurate calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ErrorCode(str, Enum):
    """
    ErrorCode
    """

    """
    allowed enum values
    """
    AUTHENTICATION_FAILED = 'authentication_failed'
    API_KEY_MISSING = 'api_key_missing'
    API_KEY_NOT_FOUND = 'api_key_not_found'
    API_KEY_REVOKED = 'api_key_revoked'
    API_KEY_INVALID = 'api_key_invalid'
    MAGIC_LINK_NOT_FOUND = 'magic_link_not_found'
    MAGIC_LINK_ALREADY_USED = 'magic_link_already_used'
    MAGIC_LINK_EXPIRED = 'magic_link_expired'
    SESSION_NOT_FOUND = 'session_not_found'
    SESSION_REVOKED = 'session_revoked'
    SESSION_EXPIRED = 'session_expired'
    EXCHANGE_CODE_NOT_FOUND = 'exchange_code_not_found'
    EXCHANGE_CODE_ALREADY_USED = 'exchange_code_already_used'
    IP_RATE_LIMIT_EXCEEDED = 'ip_rate_limit_exceeded'
    BURST_LIMIT_EXCEEDED = 'burst_limit_exceeded'
    MONTHLY_USAGE_LIMIT_EXCEEDED = 'monthly_usage_limit_exceeded'
    MAGIC_LINK_IP_LIMIT_EXCEEDED = 'magic_link_ip_limit_exceeded'
    MAGIC_LINK_EMAIL_LIMIT_EXCEEDED = 'magic_link_email_limit_exceeded'
    EXCHANGE_CODE_ATTEMPT_LIMIT_EXCEEDED = 'exchange_code_attempt_limit_exceeded'
    VALIDATION_ERROR = 'validation_error'
    INVALID_EMAIL = 'invalid_email'
    INVALID_KEY_NAME = 'invalid_key_name'
    INVALID_REQUEST_BODY = 'invalid_request_body'
    DATE_OUT_OF_SUPPORTED_RANGE = 'date_out_of_supported_range'
    POLAR_LATITUDE_UNSUPPORTED = 'polar_latitude_unsupported'
    SUN_CALCULATION_FAILED = 'sun_calculation_failed'
    SOLAR_DAY_OUT_OF_RANGE = 'solar_day_out_of_range'
    EPHEMERIS_UNAVAILABLE = 'ephemeris_unavailable'
    LOCATION_REQUIRED = 'location_required'
    GEOCODE_QUERY_TOO_SHORT = 'geocode_query_too_short'
    PLAN_NOT_FOUND = 'plan_not_found'
    ACCOUNT_NOT_FOUND = 'account_not_found'
    KEY_NOT_FOUND = 'key_not_found'
    SUBSCRIPTION_NOT_FOUND = 'subscription_not_found'
    CITY_NOT_FOUND = 'city_not_found'
    INTERPRETATION_NOT_FOUND = 'interpretation_not_found'
    RESOURCE_NOT_FOUND = 'resource_not_found'
    ENDPOINT_RESTRICTED = 'endpoint_restricted'
    OWNERSHIP_DENIED = 'ownership_denied'
    INSUFFICIENT_TIER = 'insufficient_tier'
    PAYMENT_VERIFICATION_FAILED = 'payment_verification_failed'
    ORDER_CREATION_FAILED = 'order_creation_failed'
    ALREADY_ON_PLAN = 'already_on_plan'
    MAX_KEYS_EXCEEDED = 'max_keys_exceeded'
    SUBSCRIPTION_EXPIRED = 'subscription_expired'
    PAYMENT_PROVIDER_UNAVAILABLE = 'payment_provider_unavailable'
    PAYMENT_REQUEST_INVALID = 'payment_request_invalid'
    PAYLOAD_TOO_LARGE = 'payload_too_large'
    EMAIL_DELIVERY_FAILED = 'email_delivery_failed'
    GEOCODE_UNAVAILABLE = 'geocode_unavailable'
    DEPENDENCY_UNAVAILABLE = 'dependency_unavailable'
    INTERNAL_ERROR = 'internal_error'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ErrorCode from a JSON string"""
        return cls(json.loads(json_str))


