# coding: utf-8

"""
    Asterwise API

    Astrology and divination API — Vedic and Western astrology, numerology, tarot, crystals, dreams, and horoscopes. Send birth data, get accurate calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from asterwise.models.eclipse_local import EclipseLocal
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class FestivalEclipse(BaseModel):
    """
    FestivalEclipse
    """ # noqa: E501
    body: StrictStr = Field(description="sun or moon.")
    kind: StrictStr = Field(description="total, annular, hybrid, partial or penumbral.")
    greatest: StrictStr = Field(description="Instant of greatest eclipse (anywhere on Earth), local time.")
    visible_here: StrictBool = Field(description="Whether any part is visible from the requested location.")
    local: Optional[EclipseLocal] = None
    __properties: ClassVar[List[str]] = ["body", "kind", "greatest", "visible_here", "local"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FestivalEclipse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of local
        if self.local:
            _dict['local'] = self.local.to_dict()
        # set to None if local (nullable) is None
        # and model_fields_set contains the field
        if self.local is None and "local" in self.model_fields_set:
            _dict['local'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FestivalEclipse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "body": obj.get("body"),
            "kind": obj.get("kind"),
            "greatest": obj.get("greatest"),
            "visible_here": obj.get("visible_here"),
            "local": EclipseLocal.from_dict(obj["local"]) if obj.get("local") is not None else None
        })
        return _obj


