# coding: utf-8

"""
    Asterwise API

    Astrology and divination API — Vedic and Western astrology, numerology, tarot, crystals, dreams, and horoscopes. Send birth data, get accurate calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GemstoneResponse(BaseModel):
    """
    GemstoneResponse
    """ # noqa: E501
    primary: Dict[str, Any] = Field(description="Lagna lord's gem: planet, reason, gemstone, substitute_gemstone, metal, colour, note. The lagna lord is always a functional benefic (BPHS Ch.34), so this is never withheld for lordship; it can still be contraindicated when the planet is debilitated or combust. Every slot also carries `contraindicated` (bool) and `caution` (string or null): when the slot's planet appears in `contraindicated`, the slot says `contraindicated: true` with a caution — do not wear that gem for this role. A 5th/9th lord that also owns a dusthana keeps `contraindicated: false` with a caution naming the dusthana.")
    secondary: Optional[Dict[str, Any]] = None
    yogakaraka_gem: Optional[Dict[str, Any]] = None
    fifth_lord_gem: Optional[Dict[str, Any]] = None
    ninth_lord_gem: Optional[Dict[str, Any]] = None
    atmakaraka_gem: Optional[Dict[str, Any]] = None
    contraindicated: List[Optional[Dict[str, Any]]] = Field(description="Planets whose gem must not be worn in this chart (planet, gemstone, reason): dusthana (6/8/12) lords that own no trikona, debilitated planets, combust planets. Same rule as POST /v1/crystals/recommend/natal.")
    note: StrictStr
    __properties: ClassVar[List[str]] = ["primary", "secondary", "yogakaraka_gem", "fifth_lord_gem", "ninth_lord_gem", "atmakaraka_gem", "contraindicated", "note"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GemstoneResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if secondary (nullable) is None
        # and model_fields_set contains the field
        if self.secondary is None and "secondary" in self.model_fields_set:
            _dict['secondary'] = None

        # set to None if yogakaraka_gem (nullable) is None
        # and model_fields_set contains the field
        if self.yogakaraka_gem is None and "yogakaraka_gem" in self.model_fields_set:
            _dict['yogakaraka_gem'] = None

        # set to None if fifth_lord_gem (nullable) is None
        # and model_fields_set contains the field
        if self.fifth_lord_gem is None and "fifth_lord_gem" in self.model_fields_set:
            _dict['fifth_lord_gem'] = None

        # set to None if ninth_lord_gem (nullable) is None
        # and model_fields_set contains the field
        if self.ninth_lord_gem is None and "ninth_lord_gem" in self.model_fields_set:
            _dict['ninth_lord_gem'] = None

        # set to None if atmakaraka_gem (nullable) is None
        # and model_fields_set contains the field
        if self.atmakaraka_gem is None and "atmakaraka_gem" in self.model_fields_set:
            _dict['atmakaraka_gem'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GemstoneResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "primary": obj.get("primary"),
            "secondary": obj.get("secondary"),
            "yogakaraka_gem": obj.get("yogakaraka_gem"),
            "fifth_lord_gem": obj.get("fifth_lord_gem"),
            "ninth_lord_gem": obj.get("ninth_lord_gem"),
            "atmakaraka_gem": obj.get("atmakaraka_gem"),
            "contraindicated": obj.get("contraindicated"),
            "note": obj.get("note")
        })
        return _obj


