# coding: utf-8

"""
    Asterwise API

    Astrology and divination API — Vedic and Western astrology, numerology, tarot, crystals, dreams, and horoscopes. Send birth data, get accurate calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List
from asterwise.models.ghatak_masa import GhatakMasa
from asterwise.models.ghatak_nakshatra import GhatakNakshatra
from asterwise.models.ghatak_tithi import GhatakTithi
from asterwise.models.ghatak_vara import GhatakVara
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GhatakParameters(BaseModel):
    """
    GhatakParameters
    """ # noqa: E501
    masa: GhatakMasa
    tithi: GhatakTithi
    vara: GhatakVara
    nakshatra: GhatakNakshatra
    __properties: ClassVar[List[str]] = ["masa", "tithi", "vara", "nakshatra"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GhatakParameters from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of masa
        if self.masa:
            _dict['masa'] = self.masa.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tithi
        if self.tithi:
            _dict['tithi'] = self.tithi.to_dict()
        # override the default output from pydantic by calling `to_dict()` of vara
        if self.vara:
            _dict['vara'] = self.vara.to_dict()
        # override the default output from pydantic by calling `to_dict()` of nakshatra
        if self.nakshatra:
            _dict['nakshatra'] = self.nakshatra.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GhatakParameters from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "masa": GhatakMasa.from_dict(obj["masa"]) if obj.get("masa") is not None else None,
            "tithi": GhatakTithi.from_dict(obj["tithi"]) if obj.get("tithi") is not None else None,
            "vara": GhatakVara.from_dict(obj["vara"]) if obj.get("vara") is not None else None,
            "nakshatra": GhatakNakshatra.from_dict(obj["nakshatra"]) if obj.get("nakshatra") is not None else None
        })
        return _obj


