# coding: utf-8

"""
    Asterwise API

    Astrology and divination API — Vedic and Western astrology, numerology, tarot, crystals, dreams, and horoscopes. Send birth data, get accurate calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class KPPlanet(BaseModel):
    """
    KPPlanet
    """ # noqa: E501
    longitude: Union[StrictFloat, StrictInt] = Field(description="Sidereal longitude (KP ayanamsa), degrees 0-360.")
    rashi_index: StrictInt = Field(description="Sign index, 0 = Mesha … 11 = Meena.")
    rashi: StrictStr
    degree: Union[StrictFloat, StrictInt] = Field(description="Degrees within the sign.")
    is_retrograde: StrictBool = Field(description="True when the longitude speed is negative. Rahu and Ketu are the mean node, which is always retrograde.")
    house: StrictInt = Field(description="KP house (1-12), cusp to cusp: from cusp h up to, not including, cusp h+1 of the sidereal Placidus cusps. A planet exactly on a cusp is in the house that cusp starts.")
    rasi_house: StrictInt = Field(description="Whole-sign house (1-12) counted from the lagna sign, for comparison with Parashari charts.")
    nakshatra_index: StrictInt = Field(description="Nakshatra index 0-26.")
    nakshatra_lord: StrictStr = Field(description="Star lord (nakshatra lord).")
    sub_lord: StrictStr = Field(description="KP sub-lord.")
    __properties: ClassVar[List[str]] = ["longitude", "rashi_index", "rashi", "degree", "is_retrograde", "house", "rasi_house", "nakshatra_index", "nakshatra_lord", "sub_lord"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of KPPlanet from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of KPPlanet from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "longitude": obj.get("longitude"),
            "rashi_index": obj.get("rashi_index"),
            "rashi": obj.get("rashi"),
            "degree": obj.get("degree"),
            "is_retrograde": obj.get("is_retrograde"),
            "house": obj.get("house"),
            "rasi_house": obj.get("rasi_house"),
            "nakshatra_index": obj.get("nakshatra_index"),
            "nakshatra_lord": obj.get("nakshatra_lord"),
            "sub_lord": obj.get("sub_lord")
        })
        return _obj


