# coding: utf-8

"""
    Asterwise API

    Astrology and divination API — Vedic and Western astrology, numerology, tarot, crystals, dreams, and horoscopes. Send birth data, get accurate calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from asterwise.models.kp_ruling_planet_body import KPRulingPlanetBody
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class KPRulingPlanetsResponse(BaseModel):
    """
    KPRulingPlanetsResponse
    """ # noqa: E501
    ayanamsa: StrictStr
    target_utc: StrictStr = Field(description="The instant used, ISO 8601 UTC.")
    target_timezone: StrictStr = Field(description="Time zone used to read `target_date`/`target_time` and for the sunrise-based day lord.")
    local_time_status: Optional[StrictStr] = Field(default='ok', description="How `target_date`/`target_time` was read. 'nonexistent': the local time fell in a daylight-saving gap and was read with the offset in force before the change (moved forward by the gap). 'ambiguous': the local time occurred twice and the first occurrence was used. 'ok' otherwise, including when the current instant was used.")
    day_lord: StrictStr
    moon: KPRulingPlanetBody
    ascendant: KPRulingPlanetBody
    ruling_planets: List[StrictStr]
    __properties: ClassVar[List[str]] = ["ayanamsa", "target_utc", "target_timezone", "local_time_status", "day_lord", "moon", "ascendant", "ruling_planets"]

    @field_validator('local_time_status')
    def local_time_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ok', 'nonexistent', 'ambiguous']):
            raise ValueError("must be one of enum values ('ok', 'nonexistent', 'ambiguous')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of KPRulingPlanetsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of moon
        if self.moon:
            _dict['moon'] = self.moon.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ascendant
        if self.ascendant:
            _dict['ascendant'] = self.ascendant.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of KPRulingPlanetsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ayanamsa": obj.get("ayanamsa"),
            "target_utc": obj.get("target_utc"),
            "target_timezone": obj.get("target_timezone"),
            "local_time_status": obj.get("local_time_status") if obj.get("local_time_status") is not None else 'ok',
            "day_lord": obj.get("day_lord"),
            "moon": KPRulingPlanetBody.from_dict(obj["moon"]) if obj.get("moon") is not None else None,
            "ascendant": KPRulingPlanetBody.from_dict(obj["ascendant"]) if obj.get("ascendant") is not None else None,
            "ruling_planets": obj.get("ruling_planets")
        })
        return _obj


