# coding: utf-8

"""
    Asterwise API

    Astrology and divination API — Vedic and Western astrology, numerology, tarot, crystals, dreams, and horoscopes. Send birth data, get accurate calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from asterwise.models.lal_kitab_ascendant import LalKitabAscendant
from asterwise.models.lal_kitab_not_remediable import LalKitabNotRemediable
from asterwise.models.lal_kitab_planet_remedy import LalKitabPlanetRemedy
from asterwise.models.lal_kitab_rin_remedy import LalKitabRinRemedy
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class LalKitabRemediesResponse(BaseModel):
    """
    LalKitabRemediesResponse
    """ # noqa: E501
    system: StrictStr
    ayanamsa: StrictStr
    birth_time_provided: Optional[StrictBool] = Field(default=True, description="False when no birth time was given: a sunrise chart is used, so the lagna and every house are approximate.")
    ascendant: LalKitabAscendant
    remedies: List[LalKitabPlanetRemedy] = Field(description="Planets with a doubtful effect and a malefic indication, in the order Sun, Moon, Mars, Mercury, Jupiter, Venus, Saturn, Rahu, Ketu.")
    not_remediable: List[LalKitabNotRemediable] = Field(description="Planets with a malefic indication but a fixed (grah phal) effect, which Lal Kitab says remedies cannot change.")
    rin_remedies: List[LalKitabRinRemedy]
    rule: StrictStr
    sources: List[StrictStr]
    __properties: ClassVar[List[str]] = ["system", "ayanamsa", "birth_time_provided", "ascendant", "remedies", "not_remediable", "rin_remedies", "rule", "sources"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LalKitabRemediesResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of ascendant
        if self.ascendant:
            _dict['ascendant'] = self.ascendant.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in remedies (list)
        _items = []
        if self.remedies:
            for _item_remedies in self.remedies:
                if _item_remedies:
                    _items.append(_item_remedies.to_dict())
            _dict['remedies'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in not_remediable (list)
        _items = []
        if self.not_remediable:
            for _item_not_remediable in self.not_remediable:
                if _item_not_remediable:
                    _items.append(_item_not_remediable.to_dict())
            _dict['not_remediable'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in rin_remedies (list)
        _items = []
        if self.rin_remedies:
            for _item_rin_remedies in self.rin_remedies:
                if _item_rin_remedies:
                    _items.append(_item_rin_remedies.to_dict())
            _dict['rin_remedies'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LalKitabRemediesResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "system": obj.get("system"),
            "ayanamsa": obj.get("ayanamsa"),
            "birth_time_provided": obj.get("birth_time_provided") if obj.get("birth_time_provided") is not None else True,
            "ascendant": LalKitabAscendant.from_dict(obj["ascendant"]) if obj.get("ascendant") is not None else None,
            "remedies": [LalKitabPlanetRemedy.from_dict(_item) for _item in obj["remedies"]] if obj.get("remedies") is not None else None,
            "not_remediable": [LalKitabNotRemediable.from_dict(_item) for _item in obj["not_remediable"]] if obj.get("not_remediable") is not None else None,
            "rin_remedies": [LalKitabRinRemedy.from_dict(_item) for _item in obj["rin_remedies"]] if obj.get("rin_remedies") is not None else None,
            "rule": obj.get("rule"),
            "sources": obj.get("sources")
        })
        return _obj


