# coding: utf-8

"""
    Asterwise API

    Vedic astrology, numerology, horoscope, and PDF report API. Send birth data, get accurate sidereal calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class LifePathResponse(BaseModel):
    """
    LifePathResponse
    """ # noqa: E501
    life_path_number: StrictInt = Field(description="Computed life path number")
    is_master_number: StrictBool = Field(description="Whether life path is a master number")
    karmic_debt_number: Optional[StrictInt]
    interpretation: StrictStr = Field(description="Narrative interpretation for life path number")
    keywords: List[Optional[StrictStr]] = Field(description="Keywords associated with the life path number")
    __properties: ClassVar[List[str]] = ["life_path_number", "is_master_number", "karmic_debt_number", "interpretation", "keywords"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LifePathResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if karmic_debt_number (nullable) is None
        # and model_fields_set contains the field
        if self.karmic_debt_number is None and "karmic_debt_number" in self.model_fields_set:
            _dict['karmic_debt_number'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LifePathResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "life_path_number": obj.get("life_path_number"),
            "is_master_number": obj.get("is_master_number"),
            "karmic_debt_number": obj.get("karmic_debt_number"),
            "interpretation": obj.get("interpretation"),
            "keywords": obj.get("keywords")
        })
        return _obj


