# coding: utf-8

"""
    Asterwise API

    Astrology and divination API — Vedic and Western astrology, numerology, tarot, crystals, dreams, and horoscopes. Send birth data, get accurate calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from asterwise.models.lo_shu_number_entry import LoShuNumberEntry
from asterwise.models.lo_shu_plane_entry import LoShuPlaneEntry
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class LoShuResponse(BaseModel):
    """
    LoShuResponse
    """ # noqa: E501
    birth_date: StrictStr
    grid: List[List[StrictInt]]
    present_numbers: List[StrictInt]
    missing_numbers: List[StrictInt]
    repeated_numbers: List[StrictInt]
    plane_analysis: Dict[str, LoShuPlaneEntry]
    number_analysis: Dict[str, LoShuNumberEntry]
    __properties: ClassVar[List[str]] = ["birth_date", "grid", "present_numbers", "missing_numbers", "repeated_numbers", "plane_analysis", "number_analysis"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LoShuResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in plane_analysis (dict)
        _field_dict = {}
        if self.plane_analysis:
            for _key_plane_analysis in self.plane_analysis:
                if self.plane_analysis[_key_plane_analysis]:
                    _field_dict[_key_plane_analysis] = self.plane_analysis[_key_plane_analysis].to_dict()
            _dict['plane_analysis'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in number_analysis (dict)
        _field_dict = {}
        if self.number_analysis:
            for _key_number_analysis in self.number_analysis:
                if self.number_analysis[_key_number_analysis]:
                    _field_dict[_key_number_analysis] = self.number_analysis[_key_number_analysis].to_dict()
            _dict['number_analysis'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LoShuResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "birth_date": obj.get("birth_date"),
            "grid": obj.get("grid"),
            "present_numbers": obj.get("present_numbers"),
            "missing_numbers": obj.get("missing_numbers"),
            "repeated_numbers": obj.get("repeated_numbers"),
            "plane_analysis": dict(
                (_k, LoShuPlaneEntry.from_dict(_v))
                for _k, _v in obj["plane_analysis"].items()
            )
            if obj.get("plane_analysis") is not None
            else None,
            "number_analysis": dict(
                (_k, LoShuNumberEntry.from_dict(_v))
                for _k, _v in obj["number_analysis"].items()
            )
            if obj.get("number_analysis") is not None
            else None
        })
        return _obj


