# coding: utf-8

"""
    Asterwise API

    Vedic astrology, numerology, horoscope, and PDF report API. Send birth data, get accurate sidereal calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MoonPhaseResponse(BaseModel):
    """
    MoonPhaseResponse
    """ # noqa: E501
    var_date: StrictStr = Field(description="Date in YYYY-MM-DD format", alias="date")
    phase_name: StrictStr = Field(description="Current phase name")
    phase_angle: Union[StrictFloat, StrictInt] = Field(description="Phase angle in degrees (0-360). 0=New Moon, 180=Full Moon")
    illumination_pct: Union[StrictFloat, StrictInt] = Field(description="Percentage of Moon disk illuminated (0-100)")
    moon_age_days: Union[StrictFloat, StrictInt] = Field(description="Days elapsed since last New Moon (0 to 29.53)")
    moon_longitude: Union[StrictFloat, StrictInt] = Field(description="Tropical ecliptic longitude of Moon (0-360)")
    sun_longitude: Union[StrictFloat, StrictInt] = Field(description="Tropical ecliptic longitude of Sun (0-360)")
    is_waxing: StrictBool = Field(description="True if Moon is waxing (phase_angle < 180)")
    next_phase_name: StrictStr = Field(description="Name of the next major phase")
    next_phase_date: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["date", "phase_name", "phase_angle", "illumination_pct", "moon_age_days", "moon_longitude", "sun_longitude", "is_waxing", "next_phase_name", "next_phase_date"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MoonPhaseResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if next_phase_date (nullable) is None
        # and model_fields_set contains the field
        if self.next_phase_date is None and "next_phase_date" in self.model_fields_set:
            _dict['next_phase_date'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MoonPhaseResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "date": obj.get("date"),
            "phase_name": obj.get("phase_name"),
            "phase_angle": obj.get("phase_angle"),
            "illumination_pct": obj.get("illumination_pct"),
            "moon_age_days": obj.get("moon_age_days"),
            "moon_longitude": obj.get("moon_longitude"),
            "sun_longitude": obj.get("sun_longitude"),
            "is_waxing": obj.get("is_waxing"),
            "next_phase_name": obj.get("next_phase_name"),
            "next_phase_date": obj.get("next_phase_date")
        })
        return _obj


