# coding: utf-8

"""
    Asterwise API

    Astrology and divination API — Vedic and Western astrology, numerology, tarot, crystals, dreams, and horoscopes. Send birth data, get accurate calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MuhurtaCriteria(BaseModel):
    """
    MuhurtaCriteria
    """ # noqa: E501
    nakshatras: List[StrictStr]
    recommended_nakshatras: List[StrictStr]
    tithis: List[StrictStr]
    weekdays: List[StrictStr]
    preferred_lagnas: List[StrictStr]
    avoided_seasons: List[StrictStr]
    avoided_periods: List[StrictStr]
    daytime_only: StrictBool
    __properties: ClassVar[List[str]] = ["nakshatras", "recommended_nakshatras", "tithis", "weekdays", "preferred_lagnas", "avoided_seasons", "avoided_periods", "daytime_only"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MuhurtaCriteria from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MuhurtaCriteria from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "nakshatras": obj.get("nakshatras"),
            "recommended_nakshatras": obj.get("recommended_nakshatras"),
            "tithis": obj.get("tithis"),
            "weekdays": obj.get("weekdays"),
            "preferred_lagnas": obj.get("preferred_lagnas"),
            "avoided_seasons": obj.get("avoided_seasons"),
            "avoided_periods": obj.get("avoided_periods"),
            "daytime_only": obj.get("daytime_only")
        })
        return _obj


