# coding: utf-8

"""
    Asterwise API

    Astrology and divination API — Vedic and Western astrology, numerology, tarot, crystals, dreams, and horoscopes. Send birth data, get accurate calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from asterwise.models.pitru_ninth_lord_analysis import PitruNinthLordAnalysis
from asterwise.models.pitru_sun_analysis import PitruSunAnalysis
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PitruDoshaResponse(BaseModel):
    """
    PitruDoshaResponse
    """ # noqa: E501
    present: StrictBool
    severity: Optional[StrictStr] = None
    severity_note: Optional[StrictStr] = None
    combinations_triggered: List[StrictStr]
    combinations_count: StrictInt
    sun_analysis: PitruSunAnalysis
    ninth_lord_analysis: PitruNinthLordAnalysis
    all_factors: List[StrictStr]
    cancellations: List[StrictStr]
    interpretation: StrictStr
    classical_symptoms: List[StrictStr]
    remedies: List[StrictStr]
    __properties: ClassVar[List[str]] = ["present", "severity", "severity_note", "combinations_triggered", "combinations_count", "sun_analysis", "ninth_lord_analysis", "all_factors", "cancellations", "interpretation", "classical_symptoms", "remedies"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PitruDoshaResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of sun_analysis
        if self.sun_analysis:
            _dict['sun_analysis'] = self.sun_analysis.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ninth_lord_analysis
        if self.ninth_lord_analysis:
            _dict['ninth_lord_analysis'] = self.ninth_lord_analysis.to_dict()
        # set to None if severity (nullable) is None
        # and model_fields_set contains the field
        if self.severity is None and "severity" in self.model_fields_set:
            _dict['severity'] = None

        # set to None if severity_note (nullable) is None
        # and model_fields_set contains the field
        if self.severity_note is None and "severity_note" in self.model_fields_set:
            _dict['severity_note'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PitruDoshaResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "present": obj.get("present"),
            "severity": obj.get("severity"),
            "severity_note": obj.get("severity_note"),
            "combinations_triggered": obj.get("combinations_triggered"),
            "combinations_count": obj.get("combinations_count"),
            "sun_analysis": PitruSunAnalysis.from_dict(obj["sun_analysis"]) if obj.get("sun_analysis") is not None else None,
            "ninth_lord_analysis": PitruNinthLordAnalysis.from_dict(obj["ninth_lord_analysis"]) if obj.get("ninth_lord_analysis") is not None else None,
            "all_factors": obj.get("all_factors"),
            "cancellations": obj.get("cancellations"),
            "interpretation": obj.get("interpretation"),
            "classical_symptoms": obj.get("classical_symptoms"),
            "remedies": obj.get("remedies")
        })
        return _obj


