# coding: utf-8

"""
    Asterwise API

    Vedic astrology, numerology, horoscope, and PDF report API. Send birth data, get accurate sidereal calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PlanetPosition(BaseModel):
    """
    PlanetPosition
    """ # noqa: E501
    planet: StrictStr = Field(description="Planet name")
    sign: StrictStr = Field(description="Zodiac sign name where the planet is placed")
    sign_num: Annotated[int, Field(le=11, strict=True, ge=0)] = Field(description="Zero-based zodiac sign index")
    degree: Union[StrictFloat, StrictInt] = Field(description="Sidereal longitude in degrees")
    nakshatra: StrictStr = Field(description="Nakshatra name for planetary placement")
    nakshatra_pada: Annotated[int, Field(le=4, strict=True, ge=1)] = Field(description="Nakshatra pada index")
    is_retrograde: StrictBool = Field(description="Whether the planet is retrograde")
    is_combust: Optional[StrictBool] = Field(default=False, description="True if the planet is within its combustion orb of the Sun")
    is_deep_combust: Optional[StrictBool] = Field(default=False, description="True if within 3° of the Sun (deep combustion / Gadha Moudhya)")
    house: Annotated[int, Field(le=12, strict=True, ge=1)] = Field(description="Whole-sign (Rasi) house number where the planet is placed")
    rasi_house: Optional[Annotated[int, Field(le=12, strict=True, ge=0)]] = None
    bhava_chalit_house: Optional[Annotated[int, Field(le=12, strict=True, ge=1)]] = None
    house_system_note: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["planet", "sign", "sign_num", "degree", "nakshatra", "nakshatra_pada", "is_retrograde", "is_combust", "is_deep_combust", "house", "rasi_house", "bhava_chalit_house", "house_system_note"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PlanetPosition from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if rasi_house (nullable) is None
        # and model_fields_set contains the field
        if self.rasi_house is None and "rasi_house" in self.model_fields_set:
            _dict['rasi_house'] = None

        # set to None if bhava_chalit_house (nullable) is None
        # and model_fields_set contains the field
        if self.bhava_chalit_house is None and "bhava_chalit_house" in self.model_fields_set:
            _dict['bhava_chalit_house'] = None

        # set to None if house_system_note (nullable) is None
        # and model_fields_set contains the field
        if self.house_system_note is None and "house_system_note" in self.model_fields_set:
            _dict['house_system_note'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PlanetPosition from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "planet": obj.get("planet"),
            "sign": obj.get("sign"),
            "sign_num": obj.get("sign_num"),
            "degree": obj.get("degree"),
            "nakshatra": obj.get("nakshatra"),
            "nakshatra_pada": obj.get("nakshatra_pada"),
            "is_retrograde": obj.get("is_retrograde"),
            "is_combust": obj.get("is_combust") if obj.get("is_combust") is not None else False,
            "is_deep_combust": obj.get("is_deep_combust") if obj.get("is_deep_combust") is not None else False,
            "house": obj.get("house"),
            "rasi_house": obj.get("rasi_house"),
            "bhava_chalit_house": obj.get("bhava_chalit_house"),
            "house_system_note": obj.get("house_system_note")
        })
        return _obj


