# coding: utf-8

"""
    Asterwise API

    Astrology and divination API — Vedic and Western astrology, numerology, tarot, crystals, dreams, and horoscopes. Send birth data, get accurate calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from asterwise.models.saturn_stay import SaturnStay
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SadeSatiPhase(BaseModel):
    """
    SadeSatiPhase
    """ # noqa: E501
    name: StrictStr
    description: StrictStr
    start: StrictStr = Field(description="Saturn's first entry into the phase sign.")
    end: StrictStr = Field(description="Saturn's final exit from the phase sign, after any retrograde return.")
    saturn_sign: StrictStr
    intensity: StrictStr
    segments: Optional[List[SaturnStay]] = Field(default=None, description="Every stay of Saturn in the phase sign; phases can interleave around a retrograde loop.")
    is_interrupted: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["name", "description", "start", "end", "saturn_sign", "intensity", "segments", "is_interrupted"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SadeSatiPhase from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in segments (list)
        _items = []
        if self.segments:
            for _item_segments in self.segments:
                if _item_segments:
                    _items.append(_item_segments.to_dict())
            _dict['segments'] = _items
        # set to None if is_interrupted (nullable) is None
        # and model_fields_set contains the field
        if self.is_interrupted is None and "is_interrupted" in self.model_fields_set:
            _dict['is_interrupted'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SadeSatiPhase from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "start": obj.get("start"),
            "end": obj.get("end"),
            "saturn_sign": obj.get("saturn_sign"),
            "intensity": obj.get("intensity"),
            "segments": [SaturnStay.from_dict(_item) for _item in obj["segments"]] if obj.get("segments") is not None else None,
            "is_interrupted": obj.get("is_interrupted")
        })
        return _obj


