# coding: utf-8

"""
    Asterwise API

    Vedic astrology, numerology, horoscope, and PDF report API. Send birth data, get accurate sidereal calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class StationEvent(BaseModel):
    """
    StationEvent
    """ # noqa: E501
    planet: StrictStr = Field(description="Planet name. Rahu and Ketu never have station events.")
    station_type: StrictStr = Field(description="retrograde — planet appears to reverse direction. direct — planet resumes forward motion.")
    jd: Union[StrictFloat, StrictInt] = Field(description="Julian Day number of the station moment")
    date_iso: StrictStr = Field(description="Date of station in YYYY-MM-DD format")
    longitude: Union[StrictFloat, StrictInt] = Field(description="Sidereal longitude of the planet at the moment of station")
    __properties: ClassVar[List[str]] = ["planet", "station_type", "jd", "date_iso", "longitude"]

    @field_validator('station_type')
    def station_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['retrograde', 'direct']):
            raise ValueError("must be one of enum values ('retrograde', 'direct')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StationEvent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StationEvent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "planet": obj.get("planet"),
            "station_type": obj.get("station_type"),
            "jd": obj.get("jd"),
            "date_iso": obj.get("date_iso"),
            "longitude": obj.get("longitude")
        })
        return _obj


