# coding: utf-8

"""
    Asterwise API

    Vedic astrology, numerology, horoscope, and PDF report API. Send birth data, get accurate sidereal calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TarotCardSchema(BaseModel):
    """
    TarotCardSchema
    """ # noqa: E501
    id: StrictStr = Field(description="Unique slug identifier e.g. 'the-fool'")
    name: StrictStr = Field(description="Full card name e.g. 'The Fool'")
    arcana_type: StrictStr = Field(description="'major' or 'minor'")
    suit: Optional[StrictStr] = None
    number: StrictInt = Field(description="Card number. Major arcana: 0-21. Minor arcana: 1=Ace, 11=Page, 12=Knight, 13=Queen, 14=King.")
    element: StrictStr = Field(description="Elemental correspondence: fire, water, air, earth, spirit")
    astrology_correspondence: StrictStr = Field(description="Astrological planet or sign correspondence")
    keywords_upright: List[StrictStr] = Field(description="Upright keywords")
    keywords_reversed: List[StrictStr] = Field(description="Reversed keywords")
    upright_meaning: StrictStr = Field(description="Full upright interpretation")
    reversed_meaning: StrictStr = Field(description="Full reversed interpretation")
    yes_no: StrictStr = Field(description="Yes/No polarity: 'yes', 'no', or 'maybe'")
    description: StrictStr = Field(description="Visual description of the card imagery")
    __properties: ClassVar[List[str]] = ["id", "name", "arcana_type", "suit", "number", "element", "astrology_correspondence", "keywords_upright", "keywords_reversed", "upright_meaning", "reversed_meaning", "yes_no", "description"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TarotCardSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if suit (nullable) is None
        # and model_fields_set contains the field
        if self.suit is None and "suit" in self.model_fields_set:
            _dict['suit'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TarotCardSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "arcana_type": obj.get("arcana_type"),
            "suit": obj.get("suit"),
            "number": obj.get("number"),
            "element": obj.get("element"),
            "astrology_correspondence": obj.get("astrology_correspondence"),
            "keywords_upright": obj.get("keywords_upright"),
            "keywords_reversed": obj.get("keywords_reversed"),
            "upright_meaning": obj.get("upright_meaning"),
            "reversed_meaning": obj.get("reversed_meaning"),
            "yes_no": obj.get("yes_no"),
            "description": obj.get("description")
        })
        return _obj


