# coding: utf-8

"""
    Asterwise API

    Astrology and divination API — Vedic and Western astrology, numerology, tarot, crystals, dreams, and horoscopes. Send birth data, get accurate calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class VarshaPati(BaseModel):
    """
    VarshaPati
    """ # noqa: E501
    planet: StrictStr
    role: StrictStr
    pancha_vargeeya_bala: Union[StrictFloat, StrictInt]
    kshetra_bala: Union[StrictFloat, StrictInt]
    uchcha_bala: Union[StrictFloat, StrictInt]
    election_fallback: Optional[StrictStr] = None
    moon_election: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["planet", "role", "pancha_vargeeya_bala", "kshetra_bala", "uchcha_bala", "election_fallback", "moon_election"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VarshaPati from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if election_fallback (nullable) is None
        # and model_fields_set contains the field
        if self.election_fallback is None and "election_fallback" in self.model_fields_set:
            _dict['election_fallback'] = None

        # set to None if moon_election (nullable) is None
        # and model_fields_set contains the field
        if self.moon_election is None and "moon_election" in self.model_fields_set:
            _dict['moon_election'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VarshaPati from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "planet": obj.get("planet"),
            "role": obj.get("role"),
            "pancha_vargeeya_bala": obj.get("pancha_vargeeya_bala"),
            "kshetra_bala": obj.get("kshetra_bala"),
            "uchcha_bala": obj.get("uchcha_bala"),
            "election_fallback": obj.get("election_fallback"),
            "moon_election": obj.get("moon_election")
        })
        return _obj


