# coding: utf-8

"""
    Asterwise API

    Astrology and divination API — Vedic and Western astrology, numerology, tarot, crystals, dreams, and horoscopes. Send birth data, get accurate calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from asterwise.models.varsha_pati import VarshaPati
from asterwise.models.varshaphal_muntha import VarshaphalMuntha
from asterwise.models.varshaphal_planet import VarshaphalPlanet
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class VarshaphalResponse(BaseModel):
    """
    VarshaphalResponse
    """ # noqa: E501
    target_year: StrictInt
    ayanamsa: StrictStr
    solar_return_utc: StrictStr
    solar_return_jd: Union[StrictFloat, StrictInt]
    natal_sun_longitude: Union[StrictFloat, StrictInt]
    natal_lagna: StrictStr
    natal_lagna_index: StrictInt
    year_lord: StrictStr
    muntha: VarshaphalMuntha
    planets: Dict[str, VarshaphalPlanet]
    varshaphal_ascendant_longitude: Optional[Union[StrictFloat, StrictInt]] = None
    varshaphal_ascendant_sign: Optional[StrictStr] = None
    varshaphal_ascendant_sign_index: Optional[StrictInt] = None
    varsha_pati: VarshaPati
    pancha_adhikaris: List[Optional[Dict[str, Any]]]
    pancha_vargeeya_bala: Dict[str, Union[StrictFloat, StrictInt]]
    tajika_aspects: List[Optional[Dict[str, Any]]]
    tajika_planet_pairs: List[Optional[Dict[str, Any]]]
    __properties: ClassVar[List[str]] = ["target_year", "ayanamsa", "solar_return_utc", "solar_return_jd", "natal_sun_longitude", "natal_lagna", "natal_lagna_index", "year_lord", "muntha", "planets", "varshaphal_ascendant_longitude", "varshaphal_ascendant_sign", "varshaphal_ascendant_sign_index", "varsha_pati", "pancha_adhikaris", "pancha_vargeeya_bala", "tajika_aspects", "tajika_planet_pairs"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VarshaphalResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of muntha
        if self.muntha:
            _dict['muntha'] = self.muntha.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each value in planets (dict)
        _field_dict = {}
        if self.planets:
            for _key_planets in self.planets:
                if self.planets[_key_planets]:
                    _field_dict[_key_planets] = self.planets[_key_planets].to_dict()
            _dict['planets'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of varsha_pati
        if self.varsha_pati:
            _dict['varsha_pati'] = self.varsha_pati.to_dict()
        # set to None if varshaphal_ascendant_longitude (nullable) is None
        # and model_fields_set contains the field
        if self.varshaphal_ascendant_longitude is None and "varshaphal_ascendant_longitude" in self.model_fields_set:
            _dict['varshaphal_ascendant_longitude'] = None

        # set to None if varshaphal_ascendant_sign (nullable) is None
        # and model_fields_set contains the field
        if self.varshaphal_ascendant_sign is None and "varshaphal_ascendant_sign" in self.model_fields_set:
            _dict['varshaphal_ascendant_sign'] = None

        # set to None if varshaphal_ascendant_sign_index (nullable) is None
        # and model_fields_set contains the field
        if self.varshaphal_ascendant_sign_index is None and "varshaphal_ascendant_sign_index" in self.model_fields_set:
            _dict['varshaphal_ascendant_sign_index'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VarshaphalResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "target_year": obj.get("target_year"),
            "ayanamsa": obj.get("ayanamsa"),
            "solar_return_utc": obj.get("solar_return_utc"),
            "solar_return_jd": obj.get("solar_return_jd"),
            "natal_sun_longitude": obj.get("natal_sun_longitude"),
            "natal_lagna": obj.get("natal_lagna"),
            "natal_lagna_index": obj.get("natal_lagna_index"),
            "year_lord": obj.get("year_lord"),
            "muntha": VarshaphalMuntha.from_dict(obj["muntha"]) if obj.get("muntha") is not None else None,
            "planets": dict(
                (_k, VarshaphalPlanet.from_dict(_v))
                for _k, _v in obj["planets"].items()
            )
            if obj.get("planets") is not None
            else None,
            "varshaphal_ascendant_longitude": obj.get("varshaphal_ascendant_longitude"),
            "varshaphal_ascendant_sign": obj.get("varshaphal_ascendant_sign"),
            "varshaphal_ascendant_sign_index": obj.get("varshaphal_ascendant_sign_index"),
            "varsha_pati": VarshaPati.from_dict(obj["varsha_pati"]) if obj.get("varsha_pati") is not None else None,
            "pancha_adhikaris": obj.get("pancha_adhikaris"),
            "pancha_vargeeya_bala": obj.get("pancha_vargeeya_bala"),
            "tajika_aspects": obj.get("tajika_aspects"),
            "tajika_planet_pairs": obj.get("tajika_planet_pairs")
        })
        return _obj


