# coding: utf-8

"""
    Asterwise API

    Vedic astrology, numerology, horoscope, and PDF report API. Send birth data, get accurate sidereal calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WesternPlanetPosition(BaseModel):
    """
    WesternPlanetPosition
    """ # noqa: E501
    name: StrictStr = Field(description="Planet name")
    longitude: Union[StrictFloat, StrictInt] = Field(description="Tropical ecliptic longitude 0–360°")
    sign: StrictStr = Field(description="Zodiac sign name")
    sign_index: Annotated[int, Field(le=11, strict=True, ge=0)]
    degree_in_sign: Union[StrictFloat, StrictInt] = Field(description="Degrees within sign 0–29.999")
    house: Annotated[int, Field(le=12, strict=True, ge=1)] = Field(description="House number (Placidus or chosen system)")
    is_retrograde: StrictBool
    dignity: StrictStr = Field(description="Essential dignity: domicile | exaltation | detriment | fall | peregrine")
    dignity_score: StrictInt = Field(description="Lilly dignity weight: domicile=5, exaltation=4, detriment=-5, fall=-4, peregrine=0")
    is_exaltation_degree: StrictBool = Field(description="True if planet is in the exact classical exaltation degree (Nth degree = N-1°00' to N-1°59'59\"). Always false for outer planets (no exact degree defined).")
    dignity_disputed: StrictBool = Field(description="True for outer planet (Uranus/Neptune/Pluto) exaltation/fall — no classical consensus.")
    __properties: ClassVar[List[str]] = ["name", "longitude", "sign", "sign_index", "degree_in_sign", "house", "is_retrograde", "dignity", "dignity_score", "is_exaltation_degree", "dignity_disputed"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WesternPlanetPosition from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WesternPlanetPosition from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "longitude": obj.get("longitude"),
            "sign": obj.get("sign"),
            "sign_index": obj.get("sign_index"),
            "degree_in_sign": obj.get("degree_in_sign"),
            "house": obj.get("house"),
            "is_retrograde": obj.get("is_retrograde"),
            "dignity": obj.get("dignity"),
            "dignity_score": obj.get("dignity_score"),
            "is_exaltation_degree": obj.get("is_exaltation_degree"),
            "dignity_disputed": obj.get("dignity_disputed")
        })
        return _obj


