# coding: utf-8

"""
    Asterwise API

    Astrology and divination API — Vedic and Western astrology, numerology, tarot, crystals, dreams, and horoscopes. Send birth data, get accurate calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from asterwise.models.horoscope_phase import HoroscopePhase
from asterwise.models.western_horoscope_chapter import WesternHoroscopeChapter
from asterwise.models.western_horoscope_landmark_date import WesternHoroscopeLandmarkDate
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WesternHoroscopeContent(BaseModel):
    """
    Stored Western tropical horoscope prose; no remedy field.
    """ # noqa: E501
    headline: StrictStr
    narrative: StrictStr
    career: StrictStr
    money: StrictStr
    love: StrictStr
    body: StrictStr
    power_window: Optional[StrictStr] = None
    caution_window: Optional[StrictStr] = None
    closing_message: Optional[StrictStr] = None
    phases: Optional[List[HoroscopePhase]] = None
    year_theme: Optional[StrictStr] = None
    chapters: Optional[List[WesternHoroscopeChapter]] = None
    auspicious_months: Optional[List[StrictStr]] = None
    landmark_dates: Optional[List[WesternHoroscopeLandmarkDate]] = None
    __properties: ClassVar[List[str]] = ["headline", "narrative", "career", "money", "love", "body", "power_window", "caution_window", "closing_message", "phases", "year_theme", "chapters", "auspicious_months", "landmark_dates"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WesternHoroscopeContent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in phases (list)
        _items = []
        if self.phases:
            for _item_phases in self.phases:
                if _item_phases:
                    _items.append(_item_phases.to_dict())
            _dict['phases'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in chapters (list)
        _items = []
        if self.chapters:
            for _item_chapters in self.chapters:
                if _item_chapters:
                    _items.append(_item_chapters.to_dict())
            _dict['chapters'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in landmark_dates (list)
        _items = []
        if self.landmark_dates:
            for _item_landmark_dates in self.landmark_dates:
                if _item_landmark_dates:
                    _items.append(_item_landmark_dates.to_dict())
            _dict['landmark_dates'] = _items
        # set to None if power_window (nullable) is None
        # and model_fields_set contains the field
        if self.power_window is None and "power_window" in self.model_fields_set:
            _dict['power_window'] = None

        # set to None if caution_window (nullable) is None
        # and model_fields_set contains the field
        if self.caution_window is None and "caution_window" in self.model_fields_set:
            _dict['caution_window'] = None

        # set to None if closing_message (nullable) is None
        # and model_fields_set contains the field
        if self.closing_message is None and "closing_message" in self.model_fields_set:
            _dict['closing_message'] = None

        # set to None if phases (nullable) is None
        # and model_fields_set contains the field
        if self.phases is None and "phases" in self.model_fields_set:
            _dict['phases'] = None

        # set to None if year_theme (nullable) is None
        # and model_fields_set contains the field
        if self.year_theme is None and "year_theme" in self.model_fields_set:
            _dict['year_theme'] = None

        # set to None if chapters (nullable) is None
        # and model_fields_set contains the field
        if self.chapters is None and "chapters" in self.model_fields_set:
            _dict['chapters'] = None

        # set to None if auspicious_months (nullable) is None
        # and model_fields_set contains the field
        if self.auspicious_months is None and "auspicious_months" in self.model_fields_set:
            _dict['auspicious_months'] = None

        # set to None if landmark_dates (nullable) is None
        # and model_fields_set contains the field
        if self.landmark_dates is None and "landmark_dates" in self.model_fields_set:
            _dict['landmark_dates'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WesternHoroscopeContent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "headline": obj.get("headline"),
            "narrative": obj.get("narrative"),
            "career": obj.get("career"),
            "money": obj.get("money"),
            "love": obj.get("love"),
            "body": obj.get("body"),
            "power_window": obj.get("power_window"),
            "caution_window": obj.get("caution_window"),
            "closing_message": obj.get("closing_message"),
            "phases": [HoroscopePhase.from_dict(_item) for _item in obj["phases"]] if obj.get("phases") is not None else None,
            "year_theme": obj.get("year_theme"),
            "chapters": [WesternHoroscopeChapter.from_dict(_item) for _item in obj["chapters"]] if obj.get("chapters") is not None else None,
            "auspicious_months": obj.get("auspicious_months"),
            "landmark_dates": [WesternHoroscopeLandmarkDate.from_dict(_item) for _item in obj["landmark_dates"]] if obj.get("landmark_dates") is not None else None
        })
        return _obj


