# coding: utf-8

"""
    Asterwise API

    Astrology and divination API — Vedic and Western astrology, numerology, tarot, crystals, dreams, and horoscopes. Send birth data, get accurate calculations as structured JSON.  **Base URL:** https://api.asterwise.com  **Authentication:** Bearer token — `Authorization: Bearer YOUR_API_KEY`  Get your free API key at https://asterwise.com

    The version of the OpenAPI document: 2026-03-01
    Contact: support@asterwise.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WesternEssentialDignities(BaseModel):
    """
    William Lilly's essential dignities (Christian Astrology, 1647, p.104 table).
    """ # noqa: E501
    domicile: StrictInt = Field(description="5 if the planet is in one of its own signs (houses), else 0")
    exaltation: StrictInt = Field(description="4 if the planet is in its exaltation sign (anywhere in the sign), else 0")
    triplicity: StrictInt = Field(description="3 if the planet rules the sign's element for the chart's sect, else 0. Lilly's rulers (day/night): fire Sun/Jupiter, earth Venus/Moon, air Saturn/Mercury, water Mars by day and night.")
    term: StrictInt = Field(description="2 if the degree is in the planet's term (Ptolemaic terms as printed by Lilly), else 0")
    face: StrictInt = Field(description="1 if the degree is in the planet's face (10° decans, Chaldean order), else 0")
    detriment: StrictInt = Field(description="-5 if the planet is in its detriment, else 0")
    fall: StrictInt = Field(description="-4 if the planet is in its fall, else 0")
    peregrine: StrictBool = Field(description="True when the planet has none of the five dignities (domicile, exaltation, triplicity, term, face) — Lilly's peregrine, scored -5. A planet in detriment or fall with no dignity is also peregrine.")
    total: StrictInt = Field(description="Sum of all points above plus -5 when peregrine. Dignities add up (Mercury in Virgo: 5 + 4 = 9 before term/face), as do debilities (Mercury in Pisces: -5 - 4). Range -14 to +11.")
    applicable: StrictBool = Field(description="False for Uranus, Neptune and Pluto: Lilly's scheme covers only the seven classical planets, so every score is 0 and peregrine is false.")
    system: Optional[StrictStr] = Field(default='lilly', description="Scoring system: William Lilly, Christian Astrology (1647) — table of essential dignities p.104, weights pp.101–103, debilities p.115. Mutual reception and the lunar nodes are not scored.")
    __properties: ClassVar[List[str]] = ["domicile", "exaltation", "triplicity", "term", "face", "detriment", "fall", "peregrine", "total", "applicable", "system"]

    @field_validator('system')
    def system_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['lilly']):
            raise ValueError("must be one of enum values ('lilly')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WesternEssentialDignities from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WesternEssentialDignities from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "domicile": obj.get("domicile"),
            "exaltation": obj.get("exaltation"),
            "triplicity": obj.get("triplicity"),
            "term": obj.get("term"),
            "face": obj.get("face"),
            "detriment": obj.get("detriment"),
            "fall": obj.get("fall"),
            "peregrine": obj.get("peregrine"),
            "total": obj.get("total"),
            "applicable": obj.get("applicable"),
            "system": obj.get("system") if obj.get("system") is not None else 'lilly'
        })
        return _obj


